# -*- coding: utf-8 -*-
"""3.9.7_full.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RjuAMETjPgbUzuov7XIgugiyZHiE5yJ6

# Issue Tracking + Summary (v3.9.7)
- Colab에서 바로 실행 가능한 단일 노트북
- 설치는 **datasketch만** 자동으로 수행
- 결과물: `issues_*.json/csv`, `issue_articles_map_*.csv`, `singletons_*.csv`
"""


# -*- coding: utf-8 -*-
# =========================================================
# ISSUE TRACKING + SUMMARY (KoE5 / E5)  v3.9.7 (COLAB 1-NOTEBOOK)
# - Only auto-install allowed: datasketch
# - Robust CSV/ZIP loader (korea.csv or korea.zip)
# - Domain-first clustering + cross-domain centroid merge
# - Better "merge" defaults + richer previews (merged articles listed)
# =========================================================

import os, re, json, csv, math, time, hashlib, random, sys, subprocess, zipfile, html
from pathlib import Path
from dataclasses import dataclass, asdict
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Tuple, Optional, Any, Iterable
from transformers import AutoTokenizer, AutoModel
from fastapi import FastAPI
import numpy as np
import pandas as pd
import traceback

try:
    from tqdm.auto import tqdm
except Exception:
    def tqdm(x, **kwargs):
        return x

# =============================================================================
# v3.9.7 TUNING PANEL (여기만 수정)
# =============================================================================
DEDUP_USE_MINHASH = True
DEDUP_SIM_THRESHOLD = 0.88

SUSP_MIN_CONTENT_CHARS = 90
SUSP_HEAD_MAX_CHARS = 5000
SUSP_NEED_HITS_SHORT = 2
SUSP_NEED_HITS_LONG = 3

# 오병합 방지용 기본값(엄격)
IN_DOMAIN_COS_TH = 0.89
CROSS_DOMAIN_COS_TH = 0.86
TITLE_JACC_TH = 0.16
IN_DOMAIN_TITLE_JACC_TH = 0.06
CROSS_DOMAIN_LEAD_JACC_TH = 0.08
CROSS_DOMAIN_STRONG_COS_TH = 0.93
MERGE_REQUIRE_SAME_BROAD_CAT = True
CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT = True
CONTENT_LEAD_CHARS = 900
KNN_MAX_NEIGHBORS = 100

COHESION_METRIC = "centroid_mean"
MIN_COHESION = 0.0
MIN_ISSUE_SIZE = 2

ISSUE_PREVIEW_MAX = 10
SINGLETON_PREVIEW_MAX = 0
ISSUE_ARTICLE_PREVIEW_MAX = 12
EMIT_SINGLETONS = False

EMB_BATCH_SIZE = 16

STAR_SPLIT_ENABLE = False
STAR_SIM_TH = 0.84
STAR_TITLE_JACC_TH = 0.05
MIN_REP_MIN = 0.68

# Production-facing operational guards
ENABLE_LOW_CONF_OUTPUT = True
LOW_CONF_PAIR_MAX = 30
ENABLE_LOW_CONF_REVIEW_ISSUES = True
LOW_CONF_REVIEW_MAX = 3
LOW_CONF_REVIEW_MIN_SCORE = 0.66
LOW_CONF_REVIEW_SAME_DOMAIN_STRONG_SCORE = 0.74
GENERATE_ISSUE_TITLE = True
GENERATED_TITLE_MAX_CHARS = 64
FORCE_SOURCE_TITLE = False

DB_HOST = os.getenv("DB_HOST", "project-db-cgi.smhrd.com")
DB_PORT = int(os.getenv("DB_PORT", "3307"))
DB_USER = os.getenv("DB_USER", "cgi_25K_DA1_p3_3")
DB_PASSWORD = os.getenv("DB_PASSWORD", "smhrd3")
DB_NAME = os.getenv("DB_NAME", "cgi_25K_DA1_p3_3")

# =============================================================================
# Dependency policy (IMPORTANT)
# - The ONLY allowed installation is: datasketch
# =============================================================================
def ensure_datasketch() -> None:
    try:
        import datasketch  # noqa: F401
        return
    except Exception:
        print("[INFO] datasketch not found -> installing: pip install -q datasketch")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "datasketch"])

ensure_datasketch()
from datasketch import MinHash, MinHashLSH  # noqa: E402

_HAVE_TORCH = False
_TORCH_ERR = None
try:
    import torch  # noqa: E402
    _HAVE_TORCH = True
except Exception as e:
    _TORCH_ERR = repr(e)

_HAVE_TRANSFORMERS = False
_TRANSFORMERS_ERR = None
try:
    from transformers import AutoTokenizer, AutoModel  # noqa: E402
    _HAVE_TRANSFORMERS = True
except Exception as e:
    _TRANSFORMERS_ERR = repr(e)

try:
    from sklearn.feature_extraction.text import TfidfVectorizer  # type: ignore
except Exception:
    TfidfVectorizer = None  # type: ignore

KST = timezone(timedelta(hours=9))
TOKEN_RE = re.compile(r"[A-Za-z0-9가-힣]+")
HANJA_TITLE_MAP = {
    "美": "미국",
    "日": "일본",
    "中": "중국",
    "北": "북한",
    "韓": "한국",
    "尹": "윤석열",
    "李": "이재명",
    "與": "여당",
    "野": "야당",
}

def sha1(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="ignore")).hexdigest()

def now_kst_iso() -> str:
    return datetime.now(tz=KST).isoformat(timespec="seconds")

def l2_normalize_rows(X: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(X, axis=1, keepdims=True)
    return X / (n + 1e-9)

def canonical_url(url: str) -> str:
    try:
        from urllib.parse import urlparse, parse_qsl, urlencode, urlunparse
        if not url:
            return ""
        u = str(url).strip()
        if not u:
            return ""
        if "://" not in u:
            u = "https://" + u
        p = urlparse(u)
        host = (p.netloc or "").lower()
        if host.startswith("www."):
            host = host[4:]
        path = p.path or ""
        if path != "/" and path.endswith("/"):
            path = path[:-1]

        tracking_keys = {"fbclid","gclid","yclid","igshid","mc_cid","mc_eid","_gl","spm","ref","referrer","source","src","feature"}
        q = []
        for k, v in parse_qsl(p.query, keep_blank_values=True):
            lk = (k or "").lower()
            if lk.startswith("utm_"):
                continue
            if lk in tracking_keys:
                continue
            q.append((k, v))
        q.sort(key=lambda kv: (kv[0], kv[1]))
        query = urlencode(q, doseq=True)

        new_p = (p.scheme.lower() if p.scheme else "https", host, path, "", query, "")
        return urlunparse(new_p)
    except Exception:
        return (str(url).strip() if url else "")

def row_dedup_key(url: str, title: str, content: str) -> str:
    cu = canonical_url(url)
    if cu:
        return "U:" + cu
    t = re.sub(r"\s+", " ", (title or "").strip().lower())
    c = re.sub(r"\s+", " ", (content or "").strip().lower())
    return "TC:" + sha1(t + "||" + sha1(c))

def safe_domain(url: str) -> str:
    try:
        from urllib.parse import urlparse
        d = urlparse(url).netloc.lower()
        return d[4:] if d.startswith("www.") else d
    except Exception:
        return ""

def broad_category(cat: str) -> str:
    if cat is None:
        return 'unknown'
    c = str(cat).strip().lower()
    c = c.replace('\\', '/').replace('>', '/').replace('|', '/').replace('·', '/')
    if not c:
        return 'unknown'
    return (c.split('/')[0].strip() or 'unknown')

def bucket_key_from_dt(ts: pd.Timestamp, bucket: str) -> str:
    if bucket == "day":
        return ts.strftime("%Y-%m-%d")
    if bucket == "week":
        iso = ts.isocalendar()
        return f"{iso.year}-W{int(iso.week):02d}"
    return "all"

def config_fingerprint(cfg: "PipelineConfig") -> str:
    d = asdict(cfg)
    return sha1(json.dumps(d, sort_keys=True, ensure_ascii=False))

# =============================================================================
# Config
# =============================================================================
@dataclass
class PipelineConfig:
    CSV_PATH: str
    OUT_DIR: str

    BUCKET: str = "day"
    MAX_BUCKETS: int = 2
    TARGET_BUCKETS: Optional[List[str]] = None

    E5_MODEL: str = "intfloat/multilingual-e5-large"
    DEVICE: str = "auto"

    READ_CHUNKSIZE: int = 5000
    MAX_DOCS_PER_BUCKET: int = 12000
    EMB_BATCH_SIZE: int = 16
    RANDOM_SEED: int = 42

    CLUSTER_MODE: str = "domain_merge"
    KNN_MAX_N: int = 6000
    MINHASH_TH: float = 0.65
    COS_TH: float = 0.83

    MIN_ISSUE_SIZE: int = 2
    IN_DOMAIN_COS_TH: float = 0.89
    CROSS_DOMAIN_COS_TH: float = 0.86
    TITLE_JACC_TH: float = 0.16
    IN_DOMAIN_TITLE_JACC_TH: float = 0.06
    CROSS_DOMAIN_LEAD_JACC_TH: float = 0.08
    CROSS_DOMAIN_STRONG_COS_TH: float = 0.93
    KNN_MAX_NEIGHBORS: int = 100

    MERGE_REQUIRE_SAME_BROAD_CAT: bool = True
    CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT: bool = True

    STAR_SPLIT_ENABLE: bool = False
    STAR_SIM_TH: float = 0.84
    STAR_TITLE_JACC_TH: float = 0.05
    MIN_REP_MIN: float = 0.68

    DROP_SUSPICIOUS_ROWS: bool = True
    DEDUP_USE_MINHASH: bool = True
    DEDUP_SIM_THRESHOLD: float = 0.88
    SUSP_MIN_CONTENT_CHARS: int = 90
    SUSP_HEAD_MAX_CHARS: int = 5000
    SUSP_NEED_HITS_SHORT: int = 2
    SUSP_NEED_HITS_LONG: int = 3
    COHESION_METRIC: str = "centroid_mean"
    MIN_COHESION: float = 0.0

    EMIT_SINGLETONS: bool = False
    ENABLE_LOW_CONF_OUTPUT: bool = True
    LOW_CONF_PAIR_MAX: int = 30
    ENABLE_LOW_CONF_REVIEW_ISSUES: bool = True
    LOW_CONF_REVIEW_MAX: int = 3
    LOW_CONF_REVIEW_MIN_SCORE: float = 0.66
    LOW_CONF_REVIEW_SAME_DOMAIN_STRONG_SCORE: float = 0.74
    GENERATE_ISSUE_TITLE: bool = True
    GENERATED_TITLE_MAX_CHARS: int = 64
    FORCE_SOURCE_TITLE: bool = False
    INCLUDE_ARTICLES_IN_JSON: bool = True
    RESUME: bool = True
    AUTO_SHUTDOWN: bool = False

# =============================================================================
# Text cleaning / suspicious guards
# =============================================================================
EMAIL_RE = re.compile(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}")
URL_RE = re.compile(r"https?://\S+")
WS_RE = re.compile(r"\s+")

BOILERPLATE_PATTERNS = [
    r"인터넷신문\s*등록번호.*",
    r"사업자등록번호.*",
    r"청소년\s*보호책임자.*",
    r"무단\s*전재.*금지.*",
    r"All\s*rights\s*reserved.*",
    r"기사\s*제보.*",
    r"구독\s*신청.*",
    r"Copyright.*",
    r"기자\s*=",
    r"기자\s*[a-z0-9._%+-]+@",
    r"☎\s*\d{2,4}-\d{3,4}-\d{4}",
    r"문의\s*:\s*\d{2,4}-\d{3,4}-\d{4}",
]
BOILERPLATE_RE = re.compile("|".join(f"(?:{p})" for p in BOILERPLATE_PATTERNS), flags=re.IGNORECASE)

KEYWORD_STOPWORDS = {
    "있다", "있는", "했다", "한다", "대한", "위해",
    "관련", "통해", "이번", "지난", "이날", "것으로",
    "으로", "에서", "라고", "하며", "또한", "등", "및",
    "수", "것", "정부", "시장", "기사", "기자", "뉴스",
    "사진", "영상", "현지", "오늘",
}

# Keyword-only stopwords for cleaner issue tags (do not affect other scoring paths).
KEYWORD_EXTRACT_STOPWORDS = set(KEYWORD_STOPWORDS) | {
    "대통령", "정부", "여당", "야당", "국회", "국민의힘", "민주당",
    "의원", "대표", "회장", "총리", "장관", "위원장", "사무총장", "관계자",
    "기자", "매체", "당국", "업계", "전문가",
    "말했다", "밝혔다", "전했다", "설명했다", "강조했다", "덧붙였다", "촉구했다",
    "예정", "예정이다", "가능성", "기준", "발표", "논란", "관련", "대해", "대한",
    "오전", "오후", "내일", "전날", "당일",
    "우리", "현재", "경우", "모든", "이라고", "따라",
    "보인다", "상황", "대응할", "있습니다", "이어",
    "am", "pm",
}

KW_PARTICLE_RE = re.compile(
    r"(으로는|으로|에서|에게서|에게|까지|부터|처럼|보다|마저|조차|이나|나|과|와|은|는|이|가|을|를|의|도|만|께서|께)$"
)
DATE_LIKE_TOKEN_RE = re.compile(r"^(?:\d{1,4}(?:년|월|일|시|분|초)|\d{1,2}:\d{2})$")
LOCAL_INCIDENT_TOKENS = {
    "산불", "화재", "폭발", "붕괴", "지진", "침수", "홍수", "폭우",
    "사고", "실종", "사망", "부상", "대피", "진화",
}
GEO_SUFFIXES = ("시", "군", "구", "도", "읍", "면", "동", "리")
GEO_CORE_TOKENS = {
    "서울", "부산", "대구", "인천", "광주", "대전", "울산", "세종",
    "경기", "강원", "충북", "충남", "전북", "전남", "경북", "경남", "제주",
}
KEYWORD_VERBISH_ENDINGS = (
    "한다", "했다", "된다", "됐다", "진다", "졌다",
    "이다", "였다", "있다", "없다", "같다", "난다",
)
SUMMARY_NEAR_DUP_JACC = 0.84
SUMMARY_MIN_NORM_LEN = 24
REVIEW_KEYWORD_MIN_K = 3
REVIEW_KEYWORD_BLOCKLIST = {
    "못하고", "못한", "못해", "하며", "하면서", "같은", "가운데", "현재", "이어",
}
REVIEW_KEYWORD_BAD_SUFFIXES = ("하고", "하며", "하면서", "되는", "됐다", "했다", "한다")

def normalize_text(s: str) -> str:
    s = s or ""
    s = EMAIL_RE.sub(" ", s)
    s = URL_RE.sub(" ", s)
    s = s.replace("\u200b", " ")
    s = BOILERPLATE_RE.sub(" ", s)
    s = WS_RE.sub(" ", s).strip()
    return s

def title_tokens(title: str) -> List[str]:
    toks = TOKEN_RE.findall((title or "").lower())
    return toks[:30]

def is_noise_keyword(tok: str) -> bool:
    t = (tok or "").strip().lower()
    if len(t) < 2:
        return True
    if t.isdigit():
        return True
    if t in KEYWORD_STOPWORDS:
        return True
    return False

def _strip_kw_particle(tok: str) -> str:
    t = (tok or "").strip().lower()
    if not t:
        return ""
    # Strip one or two trailing particles (e.g., "대통령은" -> "대통령").
    for _ in range(2):
        nt = KW_PARTICLE_RE.sub("", t)
        if nt == t:
            break
        t = nt
    return t

def normalize_keyword_candidate(term: str, max_tokens: int = 3) -> str:
    raw = normalize_text(html.unescape(str(term or ""))).lower()
    toks = TOKEN_RE.findall(raw)
    if not toks:
        return ""

    out: List[str] = []
    seen: set = set()
    for tok in toks:
        t = _strip_kw_particle(tok)
        if len(t) < 2:
            continue
        if t.isdigit():
            continue
        if DATE_LIKE_TOKEN_RE.match(t):
            continue
        if t in KEYWORD_EXTRACT_STOPWORDS:
            continue
        # Drop short verb-like forms that leak from sentence tails.
        if len(t) <= 6 and t.endswith(KEYWORD_VERBISH_ENDINGS):
            continue
        # Drop short verb-like tails that frequently pollute issue tags.
        if len(t) <= 4 and t.endswith(("했다", "한다", "됐다", "되는")):
            continue
        if t in seen:
            continue
        seen.add(t)
        out.append(t)
        if len(out) >= int(max_tokens):
            break

    if not out:
        return ""
    return " ".join(out)

def clean_review_keywords(
    keywords: List[str],
    representative_title: str,
    summary_lines: List[str],
    max_k: int = 6,
    min_k: int = REVIEW_KEYWORD_MIN_K
) -> List[str]:
    max_k = max(1, int(max_k))
    min_k = max(1, min(int(min_k), int(max_k)))
    focus_tokens = {t for t in title_tokens(representative_title) if not is_noise_keyword(t)}
    for ln in (summary_lines or []):
        for tok in TOKEN_RE.findall(str(ln).lower()):
            if not is_noise_keyword(tok):
                focus_tokens.add(tok)

    picked: List[str] = []
    seen: set = set()

    def _is_bad_tokens(toks: List[str]) -> bool:
        for t in toks:
            if t in REVIEW_KEYWORD_BLOCKLIST:
                return True
            if len(t) <= 5 and t.endswith(REVIEW_KEYWORD_BAD_SUFFIXES):
                return True
        return False

    def _try_add(raw_term: str, require_focus_for_single: bool = True) -> None:
        nk = normalize_keyword_candidate(str(raw_term), max_tokens=3)
        if not nk:
            return
        toks = [t for t in TOKEN_RE.findall(nk.lower()) if len(t) >= 2]
        if not toks:
            return
        if _is_bad_tokens(toks):
            return
        tok_set = set(toks)
        if require_focus_for_single and focus_tokens and len(tok_set) == 1 and not (tok_set & focus_tokens):
            return
        key = re.sub(r"\s+", "", nk.lower())
        if key in seen:
            return
        seen.add(key)
        picked.append(nk)

    # 1) strict pass
    for kw in (keywords or []):
        _try_add(kw, require_focus_for_single=True)
        if len(picked) >= int(max_k):
            return picked[: int(max_k)]

    # 2) relaxed pass when still short
    if len(picked) < int(min_k):
        for kw in (keywords or []):
            _try_add(kw, require_focus_for_single=False)
            if len(picked) >= int(min_k) or len(picked) >= int(max_k):
                break

    # 3) title/focus token backfill to satisfy minimum count with relevant tokens
    if len(picked) < int(min_k):
        for tok in title_tokens(representative_title):
            _try_add(tok, require_focus_for_single=False)
            if len(picked) >= int(min_k) or len(picked) >= int(max_k):
                break
    if len(picked) < int(min_k):
        for tok in sorted(focus_tokens):
            _try_add(tok, require_focus_for_single=False)
            if len(picked) >= int(min_k) or len(picked) >= int(max_k):
                break

    return picked[: int(max_k)]

def _extract_geo_tokens(text: str) -> set:
    toks = TOKEN_RE.findall((text or "").lower())
    out: set = set()
    for tok in toks:
        t = (tok or "").strip()
        if len(t) < 2:
            continue
        if t in GEO_CORE_TOKENS:
            out.add(t)
            continue
        if t.endswith(GEO_SUFFIXES):
            out.add(t)
    return out

def _is_local_incident_cluster(titles: List[str]) -> bool:
    tok_set: set = set()
    for t in titles:
        tok_set.update(title_tokens(t))
    return any(t in LOCAL_INCIDENT_TOKENS for t in tok_set)

def prune_geo_mismatch_members(
    members: List[int],
    titles: List[str],
    rep_idx: int,
    min_keep: int = 2
) -> Tuple[List[int], List[int]]:
    if len(members) < 3:
        return members, []

    cluster_titles = [str(titles[i]) for i in members]
    if not _is_local_incident_cluster(cluster_titles):
        return members, []

    geo_map: Dict[int, set] = {}
    freq: Dict[str, int] = {}
    for i in members:
        gs = _extract_geo_tokens(str(titles[i]))
        geo_map[i] = gs
        for g in gs:
            freq[g] = int(freq.get(g, 0) + 1)

    if not freq:
        return members, []

    anchor_min = max(2, int(math.ceil(len(members) * 0.35)))
    anchors = [g for g, c in sorted(freq.items(), key=lambda kv: (-kv[1], kv[0])) if c >= anchor_min]
    if not anchors:
        return members, []
    anchor_set = set(anchors[:2])

    rep_title = str(titles[rep_idx])
    kept: List[int] = []
    dropped: List[int] = []
    for i in members:
        gs = geo_map.get(i, set())
        if gs and (gs & anchor_set):
            kept.append(i)
            continue
        if title_jaccard(str(titles[i]), rep_title) >= 0.18:
            kept.append(i)
            continue
        dropped.append(i)

    if len(kept) < int(min_keep):
        return members, []
    return kept, dropped

def content_suspicious(title: str, content: str, cfg: PipelineConfig) -> bool:
    c = (content or "").strip()
    if len(c) < cfg.SUSP_MIN_CONTENT_CHARS:
        return True
    toks = title_tokens(title)
    if not toks:
        return False
    head = c[: cfg.SUSP_HEAD_MAX_CHARS].lower()
    hits = sum(1 for t in toks if t in head)
    need = cfg.SUSP_NEED_HITS_LONG if len(toks) >= 4 else cfg.SUSP_NEED_HITS_SHORT
    return hits < need

def drop_suspicious_rows(df: pd.DataFrame, cfg: PipelineConfig) -> Tuple[pd.DataFrame, int]:
    if df is None or len(df) == 0 or (not cfg.DROP_SUSPICIOUS_ROWS):
        return df, 0
    keep = []
    for t, c in zip(df["title"].astype(str), df["content"].astype(str)):
        keep.append(not content_suspicious(t, c, cfg))
    dropped = int((~pd.Series(keep)).sum())
    out = df.loc[keep].reset_index(drop=True)
    return out, dropped

# =============================================================================
# DEDUP
# =============================================================================
def dedup_articles(df: pd.DataFrame, cfg: PipelineConfig) -> Tuple[pd.DataFrame, int, int]:
    if df is None or len(df) == 0:
        return df, 0, 0
    df = df.copy()
    df["_dedup_key"] = [row_dedup_key(u, t, c) for u, t, c in zip(df["url"].astype(str), df["title"].astype(str), df["content"].astype(str))]
    df["_clen"] = df["content"].astype(str).str.len()
    df = df.sort_values(["_dt","_clen"], ascending=[False, False], kind="mergesort")
    before = len(df)
    df = df.drop_duplicates(subset=["_dedup_key"], keep="first").reset_index(drop=True)
    strict_dropped = before - len(df)
    df = df.drop(columns=["_dedup_key","_clen"], errors="ignore")

    minhash_dropped = 0
    if cfg.DEDUP_USE_MINHASH and len(df) > 1:
        try:
            num_perm = 64
            lsh = MinHashLSH(threshold=float(cfg.DEDUP_SIM_THRESHOLD), num_perm=num_perm)
            keep = []
            for i, (t, c) in enumerate(zip(df["title"].astype(str), df["content"].astype(str))):
                text = (t + " " + c)[:10000]
                toks = TOKEN_RE.findall(text.lower())
                if len(toks) < 8:
                    keep.append(True)
                    continue
                mh = MinHash(num_perm=num_perm)
                for w in set(toks):
                    mh.update(w.encode("utf-8"))
                hits = lsh.query(mh)
                if hits:
                    keep.append(False)
                    continue
                lsh.insert(str(i), mh)
                keep.append(True)
            before2 = len(df)
            df = df.loc[keep].reset_index(drop=True)
            minhash_dropped = before2 - len(df)
        except Exception as e:
            print("[WARN] MinHash dedup failed; keep strict only:", repr(e))
    return df, int(strict_dropped), int(minhash_dropped)

# =============================================================================
# Embedding (E5 via transformers)
# =============================================================================
def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    if _HAVE_TORCH:
        try:
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)
        except Exception:
            pass

def get_device(device: str) -> "torch.device":
    if device == "cpu":
        return torch.device("cpu")
    if device == "cuda":
        return torch.device("cuda")
    return torch.device("cuda" if torch.cuda.is_available() else "cpu")

class KoE5Embedder:
    def __init__(self, model_name: str, device: "torch.device", max_length: int = 512):
        self.device = device
        self.tok = AutoTokenizer.from_pretrained(model_name)
        self.model = AutoModel.from_pretrained(model_name).to(device)
        self.model.eval()
        self.max_length = max_length

    @staticmethod
    def _mean_pool(last_hidden, attn_mask):
        mask = attn_mask.unsqueeze(-1).expand(last_hidden.size()).float()
        return (last_hidden * mask).sum(1) / mask.sum(1).clamp(min=1e-9)

    def encode(self, texts: List[str], batch_size: int = 32) -> np.ndarray:
        outs = []
        for i in tqdm(range(0, len(texts), batch_size), desc="embed", leave=False):
            batch = texts[i:i+batch_size]
            enc = self.tok(batch, padding=True, truncation=True, max_length=self.max_length, return_tensors="pt").to(self.device)
            with torch.no_grad():
                out = self.model(**enc)
                emb = self._mean_pool(out.last_hidden_state, enc["attention_mask"])
                emb = torch.nn.functional.normalize(emb, p=2, dim=1)
            outs.append(emb.detach().cpu().numpy())
        return np.vstack(outs).astype(np.float32)

# =============================================================================
# Clustering utilities
# =============================================================================
class UnionFind:
    def __init__(self, n: int):
        self.p = list(range(n))
        self.r = [0]*n
    def find(self, x: int) -> int:
        while self.p[x] != x:
            self.p[x] = self.p[self.p[x]]
            x = self.p[x]
        return x
    def union(self, a: int, b: int) -> None:
        ra, rb = self.find(a), self.find(b)
        if ra == rb: return
        if self.r[ra] < self.r[rb]:
            self.p[ra] = rb
        elif self.r[ra] > self.r[rb]:
            self.p[rb] = ra
        else:
            self.p[rb] = ra
            self.r[ra] += 1
    def groups(self) -> Dict[int, List[int]]:
        g: Dict[int, List[int]] = {}
        for i in range(len(self.p)):
            r = self.find(i)
            g.setdefault(r, []).append(i)
        return g

def title_jaccard(a: str, b: str) -> float:
    sa = set(title_tokens(a))
    sb = set(title_tokens(b))
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / max(1, len(sa | sb))

def text_token_jaccard(a: str, b: str, max_tok: int = 120) -> float:
    ta = TOKEN_RE.findall((a or "").lower())[:max_tok]
    tb = TOKEN_RE.findall((b or "").lower())[:max_tok]
    sa, sb = set(ta), set(tb)
    if not sa or not sb:
        return 0.0
    return len(sa & sb) / max(1, len(sa | sb))

def compute_cluster_metrics(members: List[int], emb: np.ndarray, rep_idx: int, sample_pairs: int = 200) -> Dict[str, float]:
    if len(members) == 0:
        return {"centroid_mean": 0.0, "rep_mean": 0.0, "rep_min": 0.0, "intra_sample_mean": 0.0}
    m = np.array(members, dtype=int)
    E = emb[m]
    centroid = l2_normalize_rows(E.mean(axis=0, keepdims=True))
    centroid_mean = float((E @ centroid.T).mean())
    rep = emb[rep_idx:rep_idx+1]
    rep_mean = float((E @ rep.T).mean())
    rep_min = float(np.min(E @ rep.T)) if len(members) > 0 else 0.0

    intra = 0.0
    if len(m) >= 2:
        rng = np.random.default_rng(123)
        pairs = min(sample_pairs, len(m)*(len(m)-1)//2)
        s = 0.0
        for _ in range(pairs):
            i, j = rng.choice(len(m), size=2, replace=False)
            s += float(E[i] @ E[j])
        intra = s / max(1, pairs)
    return {"centroid_mean": centroid_mean, "rep_mean": rep_mean, "rep_min": rep_min, "intra_sample_mean": intra}

def pick_representative(members: List[int], emb: np.ndarray) -> int:
    if len(members) == 1:
        return members[0]
    m = np.array(members, dtype=int)
    E = emb[m]
    centroid = E.mean(axis=0)
    centroid = centroid / (np.linalg.norm(centroid) + 1e-9)
    sims = E @ centroid
    return int(m[int(np.argmax(sims))])

def ordered_by_centroid(members: List[int], emb: np.ndarray) -> List[int]:
    m = np.array(members, dtype=int)
    E = emb[m]
    centroid = E.mean(axis=0)
    centroid = centroid / (np.linalg.norm(centroid) + 1e-9)
    sims = E @ centroid
    order = list(m[np.argsort(-sims)])
    return [int(x) for x in order]

def knn_edges_cos(E: np.ndarray, idxs: np.ndarray, topk: int, th: float) -> List[Tuple[int,int]]:
    edges = []
    sub = E[idxs]
    n = sub.shape[0]
    if n <= 1:
        return edges
    for i0 in range(0, n, 512):
        A = sub[i0:i0+512]
        S = A @ sub.T
        for bi in range(S.shape[0]):
            i = i0 + bi
            row = S[bi]
            row[i] = -1.0
            k = min(topk, n-1)
            cand = np.argpartition(-row, k)[:k]
            for j in cand:
                if row[j] >= th:
                    edges.append((int(idxs[i]), int(idxs[j])))
    return edges

def cluster_domain_then_merge(
    emb: np.ndarray,
    titles: List[str],
    domain_keys: List[str],
    broad_cats: List[str],
    lead_texts: List[str],
    cfg: PipelineConfig
) -> Dict[int, List[int]]:
    n = emb.shape[0]
    uf = UnionFind(n)
    E = emb

    dom2idx: Dict[str, List[int]] = {}
    for i, d in enumerate(domain_keys):
        dom2idx.setdefault(d or "", []).append(i)

    # within domain||bcat
    for d, idx_list in dom2idx.items():
        if len(idx_list) <= 1:
            continue
        idxs = np.array(idx_list, dtype=int)
        edges = knn_edges_cos(E, idxs, topk=int(cfg.KNN_MAX_NEIGHBORS), th=float(cfg.IN_DOMAIN_COS_TH))
        for a, b in edges:
            if title_jaccard(titles[a], titles[b]) < float(cfg.IN_DOMAIN_TITLE_JACC_TH):
                continue
            uf.union(a, b)

    groups = uf.groups()
    roots = list(groups.keys())
    centroids = []
    reps = []
    for r in roots:
        mem = groups[r]
        E0 = E[np.array(mem, dtype=int)]
        c = E0.mean(axis=0)
        c = c / (np.linalg.norm(c) + 1e-9)
        centroids.append(c)
        reps.append(pick_representative(mem, E))

    C = np.vstack(centroids).astype(np.float32) if centroids else np.zeros((0, E.shape[1]), np.float32)

    # cross-domain merge: stricter guard to prevent unrelated mixed issues
    if len(roots) >= 2:
        topm = min(60, len(roots)-1)
        S = C @ C.T
        np.fill_diagonal(S, -1.0)
        for i in range(len(roots)):
            row = S[i]
            cand = np.argpartition(-row, topm)[:topm]
            for j in cand:
                if row[j] < float(cfg.CROSS_DOMAIN_COS_TH):
                    continue
                ri = reps[i]
                rj = reps[j]
                if bool(getattr(cfg, "MERGE_REQUIRE_SAME_BROAD_CAT", True)):
                    bi = (broad_cats[ri] or "unknown").strip().lower()
                    bj = (broad_cats[rj] or "unknown").strip().lower()
                    if not bool(getattr(cfg, "CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT", False)):
                        if bi == "unknown" or bj == "unknown":
                            continue
                    if bi != bj:
                        continue
                tj = title_jaccard(titles[ri], titles[rj])
                lt = text_token_jaccard(lead_texts[ri], lead_texts[rj], max_tok=140)
                allow_merge = False
                if tj >= float(cfg.TITLE_JACC_TH) and lt >= float(getattr(cfg, "CROSS_DOMAIN_LEAD_JACC_TH", 0.08)):
                    allow_merge = True
                elif row[j] >= float(getattr(cfg, "CROSS_DOMAIN_STRONG_COS_TH", 0.93)):
                    if tj >= float(cfg.TITLE_JACC_TH) or lt >= float(getattr(cfg, "CROSS_DOMAIN_LEAD_JACC_TH", 0.08)):
                        allow_merge = True
                if allow_merge:
                    uf.union(ri, rj)

    return uf.groups()

def cluster_with_lsh_cosine(emb: np.ndarray, texts: List[str], cfg: PipelineConfig) -> Dict[int, List[int]]:
    n = emb.shape[0]
    uf = UnionFind(n)
    num_perm = 128
    lsh = MinHashLSH(threshold=float(cfg.MINHASH_TH), num_perm=num_perm)

    mhs: List[Optional[MinHash]] = [None]*n
    for i, text in enumerate(tqdm(texts, desc="minhash", leave=False)):
        toks = TOKEN_RE.findall((text or "").lower())
        mh = MinHash(num_perm=num_perm)
        if not toks:
            mh.update(str(i).encode("utf-8"))
        else:
            for w in set(toks[:4000]):
                mh.update(w.encode("utf-8"))
        mhs[i] = mh
        lsh.insert(str(i), mh)

    for i in tqdm(range(n), desc="lsh-union", leave=False):
        mh = mhs[i]
        if mh is None:
            continue
        cand = lsh.query(mh)
        if len(cand) <= 1:
            continue
        vi = emb[i]
        for s in cand:
            j = int(s)
            if j <= i:
                continue
            if float(vi @ emb[j]) >= float(cfg.COS_TH):
                uf.union(i, j)
    return uf.groups()

# =============================================================================
# Keywords & summary (extractive, no extra installs)
# =============================================================================
SENT_SPLIT_RE = re.compile(r"(?<=[.!?。])\s+|\n+")
DA_SENT_BOUNDARY_RE = re.compile(r"(다\.)\s+")

def split_sentences_ko(text: str) -> List[str]:
    if not isinstance(text, str):
        return []
    t = DA_SENT_BOUNDARY_RE.sub(r"\1\n", text)
    sents = [s.strip() for s in SENT_SPLIT_RE.split(t) if s.strip()]
    sents = [s for s in sents if len(s) >= 10]
    return sents

def post_clean_summary_lines(lines: List[str]) -> List[str]:
    out, seen = [], set()
    seen_tok_sets: List[set] = []
    seen_norm: List[str] = []
    for ln in lines:
        s = (ln or "").strip()
        s = EMAIL_RE.sub(" ", s)
        s = URL_RE.sub(" ", s)
        s = BOILERPLATE_RE.sub(" ", s)
        s = WS_RE.sub(" ", s).strip()
        if not s:
            continue
        if "등록번호" in s and "사업자" in s:
            continue
        if len(s) < 8:
            continue
        if "관련 기사" in s:
            continue
        if "재판매 및 db금지" in s.lower():
            continue
        if s.count(" - ") >= 3:
            continue
        if len(re.findall(r"\d{4}\.\d{2}\.\d{2}", s)) >= 2:
            continue
        key = sha1(s.lower())
        if key in seen:
            continue
        toks = {t for t in TOKEN_RE.findall(s.lower()) if len(t) >= 2 and (not t.isdigit())}
        if toks:
            dup = False
            for prev in seen_tok_sets:
                j = len(toks & prev) / max(1, len(toks | prev))
                if j >= float(SUMMARY_NEAR_DUP_JACC):
                    dup = True
                    break
            if dup:
                continue
        norm = re.sub(r"[^A-Za-z0-9가-힣]+", "", s.lower())
        if len(norm) >= int(SUMMARY_MIN_NORM_LEN):
            near = False
            for p in seen_norm:
                if norm in p or p in norm:
                    near = True
                    break
            if near:
                continue
            seen_norm.append(norm)
        seen.add(key)
        if toks:
            seen_tok_sets.append(toks)
        out.append(s if s.startswith("-") else ("- " + s))
    return out

def extract_keywords(texts: List[str], topk: int = 10) -> List[str]:
    docs = [normalize_text(t) for t in texts if isinstance(t, str) and t.strip()]
    if not docs:
        return []
    if TfidfVectorizer is None:
        from collections import Counter
        tok = []
        for d in docs:
            tok += [normalize_keyword_candidate(w, max_tokens=1) for w in TOKEN_RE.findall(d.lower())]
        tok = [w for w in tok if w]
        return [w for w, _ in Counter(tok).most_common(topk)]
    try:
        vec = TfidfVectorizer(min_df=1, max_df=0.95, ngram_range=(1,2))
        X = vec.fit_transform(docs)
        scores = np.asarray(X.mean(axis=0)).ravel()
        terms = np.array(vec.get_feature_names_out())
        order = np.argsort(-scores)
        # Aggregate TF-IDF scores after keyword normalization.
        agg: Dict[str, float] = {}
        for i in order[: topk * 20]:
            t = normalize_keyword_candidate(str(terms[i]), max_tokens=3)
            if not t:
                continue
            agg[t] = float(agg.get(t, 0.0) + float(scores[i]))

        ranked = sorted(agg.items(), key=lambda kv: -float(kv[1]))
        picked: List[str] = []
        seen_keys: List[str] = []
        for kw, _sc in ranked:
            k = re.sub(r"\s+", "", kw.lower())
            skip = False
            for sk in seen_keys:
                # Remove exact/very-near duplicates from particle/spacing variants.
                if k == sk:
                    skip = True
                    break
                if len(k) <= 3 and (k in sk):
                    skip = True
                    break
                if len(sk) <= 3 and (sk in k):
                    skip = True
                    break
            if skip:
                continue
            picked.append(kw)
            seen_keys.append(k)
            if len(picked) >= int(topk):
                break
        return picked[:topk]
    except Exception:
        return []

def extractive_news_style_summary(texts: List[str], max_lines: int = 7, min_lines: int = 5) -> List[str]:
    joined = "\n".join([normalize_text(t) for t in texts if isinstance(t, str) and t.strip()])
    sents = split_sentences_ko(joined)
    if not sents:
        return []
    scores = None
    if TfidfVectorizer is not None:
        try:
            vec = TfidfVectorizer(min_df=1, max_df=0.95, ngram_range=(1,2))
            X = vec.fit_transform(sents)
            scores = np.asarray(X.sum(axis=1)).ravel().astype(np.float32)
        except Exception:
            scores = None
    if scores is None:
        scores = np.array([min(200, len(s)) for s in sents], dtype=np.float32)

    k = min(max_lines, len(sents))
    top_idx = np.argsort(-scores)[:k]
    top_idx = sorted(top_idx.tolist())
    lines = ["- " + sents[i] for i in top_idx]
    lines = post_clean_summary_lines(lines)
    if len(lines) < min_lines:
        lines = post_clean_summary_lines(["- " + s for s in sents[:max_lines]])
    return lines[:max_lines]

def refine_summary_lines_by_focus(
    lines: List[str],
    representative_title: str,
    keywords: List[str],
    max_lines: int = 7,
    min_lines: int = 4
) -> List[str]:
    if not lines:
        return []
    norm_lines = [ln if str(ln).strip().startswith("-") else ("- " + str(ln).strip()) for ln in lines if str(ln).strip()]
    if not norm_lines:
        return []

    title_set = {t for t in title_tokens(representative_title) if not is_noise_keyword(t)}
    kw_set: set = set()
    for kw in (keywords or []):
        for tok in TOKEN_RE.findall(str(kw).lower()):
            if not is_noise_keyword(tok):
                kw_set.add(tok)
    focus_set = title_set | kw_set
    if not focus_set:
        return post_clean_summary_lines(norm_lines)[:max_lines]

    scored: List[Tuple[int, str, float]] = []
    for idx, ln in enumerate(norm_lines):
        txt = str(ln).lstrip("- ").strip()
        toks = [t for t in TOKEN_RE.findall(txt.lower()) if not is_noise_keyword(t)]
        if not toks:
            continue
        tok_set = set(toks)
        shared_title = len(tok_set & title_set)
        shared_focus = len(tok_set & focus_set)
        score = float((2.0 * shared_title) + shared_focus)
        scored.append((idx, ln, score))
    if not scored:
        return post_clean_summary_lines(norm_lines)[:max_lines]

    strong = [x for x in scored if x[2] > 0.0]
    if len(strong) >= int(min_lines):
        picked = sorted(strong, key=lambda x: (-x[2], x[0]))[: int(max_lines)]
    else:
        need = min(int(max_lines), max(int(min_lines), len(scored)))
        picked = sorted(scored, key=lambda x: (-x[2], x[0]))[:need]
    picked = sorted(picked, key=lambda x: x[0])
    out = post_clean_summary_lines([x[1] for x in picked])
    if len(out) < int(min_lines):
        out = post_clean_summary_lines(norm_lines[: int(max_lines)])
    return out[: int(max_lines)]

def _truncate_with_ellipsis(s: str, max_chars: int) -> str:
    if max_chars <= 0:
        return ""
    if len(s) <= max_chars:
        return s
    if max_chars <= 3:
        return s[:max_chars]
    return s[: max_chars - 3].rstrip() + "..."

def _clean_title_text(s: str) -> str:
    t = html.unescape(str(s or ""))
    t = normalize_text(t)
    t = re.sub(r"\s+", " ", t).strip()
    t = re.sub(r"\s*[-|]\s*(뉴스웨이|연합뉴스|뉴시스|데일리안|머니투데이)\s*$", "", t, flags=re.IGNORECASE)
    # Drop trailing campaign/series tag blocks like: [관세 리셋 쇼크]
    t = re.sub(r"\s*\[[^\]]{1,24}\]\s*$", "", t)
    # Drop dangling unmatched bracket tail like: [...[관세 리셋 쇼크
    t = re.sub(r"\s*\[[^\]]{1,24}\s*$", "", t)
    # Drop trailing parenthetical tags like "(종합)" and dangling "(종합".
    t = re.sub(r"\s*\((?:종합|속보|단독|포토|사진|영상|1보|2보|3보)\)\s*$", "", t, flags=re.IGNORECASE)
    t = re.sub(r"\s*\((?:종합|속보|단독|포토|사진|영상|1보|2보|3보)\s*$", "", t, flags=re.IGNORECASE)
    t = t.strip(" -|:;[]()")
    return t

def _title_token_set(title: str) -> set:
    raw = str(title or "")
    out = {tok for tok in TOKEN_RE.findall(raw.lower()) if not is_noise_keyword(tok)}
    for ch, mapped in HANJA_TITLE_MAP.items():
        if ch in raw:
            for tok in TOKEN_RE.findall(mapped.lower()):
                if not is_noise_keyword(tok):
                    out.add(tok)
    return out

def _best_consensus_title(candidate_titles: List[str], keywords: List[str]) -> str:
    cleaned: List[str] = []
    seen: set = set()
    for raw in (candidate_titles or []):
        t = _clean_title_text(raw)
        if len(t) < 6:
            continue
        k = t.lower()
        if k in seen:
            continue
        seen.add(k)
        cleaned.append(t)
    if not cleaned:
        return ""

    kw_set: set = set()
    for kw in (keywords or []):
        for tok in TOKEN_RE.findall(str(kw).lower()):
            if not is_noise_keyword(tok):
                kw_set.add(tok)

    token_sets: List[set] = []
    token_freq: Dict[str, int] = {}
    for t in cleaned:
        toks = _title_token_set(t)
        token_sets.append(toks)
        for tok in toks:
            token_freq[tok] = int(token_freq.get(tok, 0)) + 1

    best_i = 0
    best_score = -1e9
    for i, t in enumerate(cleaned):
        toks = token_sets[i]
        kw_hit = len(toks & kw_set)
        consensus = sum(token_freq.get(tok, 0) for tok in toks)
        length_penalty = abs(len(t) - 34) / 34.0
        score = (3.0 * kw_hit) + (1.0 * consensus) - (0.8 * length_penalty)
        # source_title is appended first in compose_issue_title(); keep a mild stability bias
        if i == 0:
            score += 0.4
        if len(t) > 72:
            score -= 1.5
        if "[" in t or "]" in t:
            score -= 1.0
        if score > best_score or (abs(score - best_score) < 1e-9 and len(t) < len(cleaned[best_i])):
            best_score = score
            best_i = i
    return cleaned[best_i]

def compose_issue_title(
    source_title: str,
    keywords: List[str],
    summary_lines: List[str],
    max_chars: int = 64,
    candidate_titles: Optional[List[str]] = None
) -> str:
    candidates: List[str] = []
    if source_title:
        candidates.append(str(source_title))
    for t in (candidate_titles or []):
        candidates.append(str(t))
    base = _best_consensus_title(candidates, keywords)
    if not base:
        base = _clean_title_text(source_title)

    if not base:
        for ln in (summary_lines or []):
            txt = str(ln).lstrip("- ").strip()
            txt = normalize_text(txt)
            txt = re.split(r"[.?!]\s+|;\s+|:\s+", txt, maxsplit=1)[0].strip()
            txt = re.sub(r"\s+", " ", txt).strip(" -:")
            if len(txt) >= 8:
                base = txt
                break

    if not base:
        kw_parts: List[str] = []
        seen_kw: set = set()
        for kw in (keywords or []):
            k = normalize_text(str(kw))
            k = re.sub(r"\s+", " ", k).strip(" -:")
            if not k:
                continue
            lk = k.lower()
            if lk in seen_kw:
                continue
            seen_kw.add(lk)
            kw_parts.append(k)
            if len(kw_parts) >= 2:
                break
        base = (("·".join(kw_parts) + " 이슈") if kw_parts else "주요 이슈 업데이트")
    return _truncate_with_ellipsis(base, int(max_chars))

def to_kst_iso(ts_like: Any) -> str:
    ts = pd.to_datetime(ts_like, errors="coerce")
    if pd.isna(ts):
        return ""
    try:
        if getattr(ts, "tzinfo", None) is None:
            ts = ts.tz_localize(KST)
        else:
            ts = ts.tz_convert(KST)
        return ts.isoformat(timespec="seconds")
    except Exception:
        try:
            ts2 = pd.to_datetime(ts_like, errors="coerce", utc=True)
            if pd.isna(ts2):
                return ""
            return ts2.tz_convert(KST).isoformat(timespec="seconds")
        except Exception:
            return ""

# =============================================================================
# IO: load + bucket selection + caching
# =============================================================================
REQUIRED_COLS = ["url","title","thumbnail","content","date","category"]

def iter_input_sources(path: str) -> Iterable[Tuple[str, Dict[str,str]]]:
    p = Path(path)
    if p.is_file() and p.suffix.lower() == ".zip":
        zp = str(p)
        with zipfile.ZipFile(zp, "r") as z:
            for name in z.namelist():
                if name.lower().endswith(".csv"):
                    yield f"{p.name}:{name}", {"kind":"zip","zip_path":zp,"member":name}
        return
    if p.is_file():
        yield str(p), {"kind":"file","path":str(p)}
        return
    if p.is_dir():
        for fp in sorted(p.glob("*.csv")):
            yield str(fp), {"kind":"file","path":str(fp)}
        for fp in sorted(p.glob("*.zip")):
            zp = str(fp)
            with zipfile.ZipFile(zp, "r") as z:
                for name in z.namelist():
                    if name.lower().endswith(".csv"):
                        yield f"{fp.name}:{name}", {"kind":"zip","zip_path":zp,"member":name}
        return
    # Fallback pattern matching (supports absolute/relative patterns on Python 3.12).
    import glob
    for m in sorted(glob.glob(path)):
        mp = Path(m)
        if mp.is_file() and mp.suffix.lower() == ".zip":
            zp = str(mp)
            with zipfile.ZipFile(zp, "r") as z:
                for name in z.namelist():
                    if name.lower().endswith(".csv"):
                        yield f"{mp.name}:{name}", {"kind":"zip","zip_path":zp,"member":name}
            continue
        if mp.is_file():
            yield str(mp), {"kind":"file","path":str(mp)}
            continue
        if mp.is_dir():
            for fp in sorted(mp.glob("*.csv")):
                yield str(fp), {"kind":"file","path":str(fp)}
            for fp in sorted(mp.glob("*.zip")):
                zp = str(fp)
                with zipfile.ZipFile(zp, "r") as z:
                    for name in z.namelist():
                        if name.lower().endswith(".csv"):
                            yield f"{fp.name}:{name}", {"kind":"zip","zip_path":zp,"member":name}

def read_csv_chunks(source: Dict[str,str], chunksize: int, usecols: Optional[List[str]] = None) -> Iterable[pd.DataFrame]:
    kind = source.get("kind")
    if kind == "file":
        yield from pd.read_csv(source["path"], chunksize=chunksize, usecols=usecols, dtype=str, encoding_errors="ignore")
        return
    if kind == "zip":
        with zipfile.ZipFile(source["zip_path"], "r") as z:
            with z.open(source["member"], "r") as f:
                yield from pd.read_csv(f, chunksize=chunksize, usecols=usecols, dtype=str, encoding_errors="ignore")
        return
    raise ValueError(f"Unknown source kind: {kind}")

def count_buckets(cfg: PipelineConfig) -> Tuple[Dict[str,int], int]:
    counts: Dict[str,int] = {}
    dropped_no_date = 0
    for _name, h in iter_input_sources(cfg.CSV_PATH):
        for chunk in read_csv_chunks(h, cfg.READ_CHUNKSIZE, usecols=["date"]):
            if "date" not in chunk.columns:
                dropped_no_date += len(chunk)
                continue
            dts = pd.to_datetime(chunk["date"], errors="coerce", utc=True)
            miss = dts.isna()
            if miss.any():
                dts_miss = pd.to_datetime(chunk.loc[miss, "date"], errors="coerce")
                try:
                    if getattr(dts_miss.dt, "tz", None) is None:
                        dts_miss = dts_miss.dt.tz_localize(KST).dt.tz_convert("UTC")
                    else:
                        dts_miss = dts_miss.dt.tz_convert("UTC")
                except Exception:
                    dts_miss = pd.to_datetime(chunk.loc[miss, "date"], errors="coerce", utc=True)
                dts_miss = pd.to_datetime(dts_miss, errors="coerce", utc=True)
                dts.loc[miss] = dts_miss

            for v in dts:
                if pd.isna(v):
                    dropped_no_date += 1
                    continue
                ts = v.tz_convert(KST) if v.tzinfo is not None else v.tz_localize(KST)
                b = bucket_key_from_dt(ts, cfg.BUCKET)
                counts[b] = counts.get(b, 0) + 1
    return counts, dropped_no_date

def select_target_buckets(counts: Dict[str,int], cfg: PipelineConfig) -> List[str]:
    if cfg.TARGET_BUCKETS:
        return cfg.TARGET_BUCKETS
    keys = sorted(list(counts.keys()), reverse=True)
    return keys[: max(1, int(cfg.MAX_BUCKETS))]

def load_bucket_df(cfg: PipelineConfig, bucket_key: str, cache_dir: Path) -> Tuple[pd.DataFrame, Dict[str,int]]:
    rows = []
    stats = {"raw_rows":0, "dropped_no_date":0}
    out_path = cache_dir / f"stage0_raw_{bucket_key}.csv"
    if out_path.exists() and cfg.RESUME:
        try:
            df = pd.read_csv(out_path, dtype=str)
            df["_dt"] = pd.to_datetime(df["_dt"], errors="coerce")
            return df, stats
        except Exception:
            out_path.unlink(missing_ok=True)

    for _name, h in iter_input_sources(cfg.CSV_PATH):
        for chunk in read_csv_chunks(h, cfg.READ_CHUNKSIZE, usecols=None):
            stats["raw_rows"] += len(chunk)
            for c in REQUIRED_COLS:
                if c not in chunk.columns:
                    chunk[c] = ""
            dts = pd.to_datetime(chunk["date"], errors="coerce", utc=True)
            miss = dts.isna()
            if miss.any():
                dts_miss = pd.to_datetime(chunk.loc[miss, "date"], errors="coerce")
                try:
                    if getattr(dts_miss.dt, "tz", None) is None:
                        dts_miss = dts_miss.dt.tz_localize(KST).dt.tz_convert("UTC")
                    else:
                        dts_miss = dts_miss.dt.tz_convert("UTC")
                except Exception:
                    dts_miss = pd.to_datetime(chunk.loc[miss, "date"], errors="coerce", utc=True)
                dts_miss = pd.to_datetime(dts_miss, errors="coerce", utc=True)
                dts.loc[miss] = dts_miss

            keep_mask = []
            dt_keep = []
            for v in dts:
                if pd.isna(v):
                    keep_mask.append(False)
                    stats["dropped_no_date"] += 1
                    dt_keep.append(pd.NaT)
                    continue
                ts = v.tz_convert(KST) if v.tzinfo is not None else v.tz_localize(KST)
                b = bucket_key_from_dt(ts, cfg.BUCKET)
                ok = (b == bucket_key)
                keep_mask.append(ok)
                dt_keep.append(ts)
            if not any(keep_mask):
                continue

            sub = chunk.loc[keep_mask, REQUIRED_COLS].copy()
            sub["_dt"] = [dt_keep[i] for i, ok in enumerate(keep_mask) if ok]
            sub["domain"] = sub["url"].astype(str).apply(safe_domain)
            rows.append(sub)

            if sum(len(x) for x in rows) >= cfg.MAX_DOCS_PER_BUCKET:
                break

    df = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame(columns=REQUIRED_COLS + ["_dt","domain"])
    df.to_csv(out_path, index=False, encoding="utf-8-sig")
    return df, stats

# =============================================================================
# Output utils
# =============================================================================
def bucket_paths(cfg: PipelineConfig, bucket_key: str) -> Dict[str, Path]:
    out = Path(cfg.OUT_DIR)
    cache = out / "_cache" / bucket_key
    cache.mkdir(parents=True, exist_ok=True)
    return {
        "cache_dir": cache,
        "stage1": cache / "stage1_clean.csv",
        "stage2_emb": cache / "stage2_emb.npy",
        "stage2_meta": cache / "stage2_meta.json",
        "stage3": cache / "stage3_groups.json",
        "issues_json": out / f"issues_{bucket_key}.json",
        "issues_csv": out / f"issues_{bucket_key}.csv",
        "review_json": out / f"review_issues_{bucket_key}.json",
        "review_csv": out / f"review_issues_{bucket_key}.csv",
        "map_csv": out / f"issue_articles_map_{bucket_key}.csv",
        "low_conf_json": out / f"low_confidence_{bucket_key}.json",
        "low_conf_csv": out / f"low_confidence_{bucket_key}.csv",
        "single_csv": out / f"singletons_{bucket_key}.csv",
        "single_json": out / f"singletons_{bucket_key}.json",
        "done": out / f"done_{bucket_key}.ok",
    }

def write_done(path: Path, cfg: PipelineConfig, stats: Dict[str,Any]) -> None:
    payload = {"time": now_kst_iso(), "fp": config_fingerprint(cfg), "stats": stats}
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")

def issues_to_csv(issues: List[Dict[str,Any]], out_csv: Path) -> None:
    rows = []
    for it in issues:
        rows.append({
            "issue_id": it.get("issue_id",""),
            "bucket": it.get("bucket",""),
            "time_start": it.get("time_start",""),
            "time_end": it.get("time_end",""),
            "size": it.get("stats",{}).get("size",0),
            "domains": it.get("stats",{}).get("domains",0),
            "centroid_mean": it.get("stats",{}).get("centroid_mean",0.0),
            "rep_mean": it.get("stats",{}).get("rep_mean",0.0),
            "intra_sample_mean": it.get("stats",{}).get("intra_sample_mean",0.0),
            "representative_title": it.get("representative_title",""),
            "source_representative_title": it.get("source_representative_title", it.get("representative_title","")),
            "representative_url": it.get("representative_url",""),
            "keywords": "|".join(it.get("keywords",[]) or []),
            "summary": "\n".join(it.get("summary_lines",[]) or []),
        })
    pd.DataFrame(rows).to_csv(out_csv, index=False, encoding="utf-8-sig")

def low_confidence_to_csv(rows: List[Dict[str,Any]], out_csv: Path) -> None:
    cols = [
        "bucket",
        "rank",
        "score",
        "cosine",
        "title_jaccard",
        "lead_jaccard",
        "domain_a",
        "title_a",
        "url_a",
        "domain_b",
        "title_b",
        "url_b",
    ]
    if not rows:
        pd.DataFrame(columns=cols).to_csv(out_csv, index=False, encoding="utf-8-sig")
        return
    pd.DataFrame(rows, columns=cols).to_csv(out_csv, index=False, encoding="utf-8-sig")

def collect_low_confidence_pairs(
    df: pd.DataFrame,
    emb: np.ndarray,
    texts_for_embed: List[str],
    bucket_key: str,
    max_pairs: int = 30
) -> List[Dict[str,Any]]:
    n = int(len(df))
    if n <= 1:
        return []
    topk = min(6, n - 1)
    if topk <= 0:
        return []

    idxs_all = np.arange(n, dtype=int)
    edges = knn_edges_cos(emb, idxs_all, topk=topk, th=0.76)
    seen: set = set()
    rows: List[Dict[str,Any]] = []
    for a, b in edges:
        i, j = (a, b) if a < b else (b, a)
        if i == j:
            continue
        key = (int(i), int(j))
        if key in seen:
            continue
        seen.add(key)

        cos = float(emb[i] @ emb[j])
        tj = title_jaccard(str(df.loc[i, "title"]), str(df.loc[j, "title"]))
        lt = text_token_jaccard(texts_for_embed[i], texts_for_embed[j], max_tok=140)
        # Keep near-miss pairs useful for QA triage.
        if cos < 0.80 and tj < 0.05 and lt < 0.06:
            continue
        score = (0.70 * cos) + (0.15 * tj) + (0.15 * lt)

        ra = df.loc[i]
        rb = df.loc[j]
        rows.append({
            "bucket": bucket_key,
            "rank": 0,
            "score": float(score),
            "cosine": float(cos),
            "title_jaccard": float(tj),
            "lead_jaccard": float(lt),
            "domain_a": str(ra.get("domain", "")),
            "title_a": str(ra.get("title", "")),
            "url_a": str(ra.get("url", "")),
            "domain_b": str(rb.get("domain", "")),
            "title_b": str(rb.get("title", "")),
            "url_b": str(rb.get("url", "")),
        })

    rows = sorted(rows, key=lambda x: (-float(x["score"]), -float(x["cosine"])))
    rows = rows[: max(1, int(max_pairs))]
    for k, r in enumerate(rows, start=1):
        r["rank"] = int(k)
    return rows

def build_review_issues_from_low_conf(
    df: pd.DataFrame,
    low_conf_rows: List[Dict[str,Any]],
    bucket_key: str,
    max_items: int = 3,
    min_score: float = 0.66,
    same_domain_strong_score: float = 0.74,
    generate_title: bool = True,
    title_max_chars: int = 64,
    force_source_title: bool = False
) -> List[Dict[str,Any]]:
    if df is None or len(df) == 0 or not low_conf_rows:
        return []

    url2idx: Dict[str, int] = {}
    c_url2idx: Dict[str, int] = {}
    for i, u in enumerate(df["url"].astype(str).tolist()):
        if u and u not in url2idx:
            url2idx[u] = int(i)
        cu = canonical_url(u)
        if cu and cu not in c_url2idx:
            c_url2idx[cu] = int(i)

    def find_idx(u: str) -> Optional[int]:
        if u in url2idx:
            return int(url2idx[u])
        cu = canonical_url(u)
        if cu in c_url2idx:
            return int(c_url2idx[cu])
        return None

    review_issues: List[Dict[str,Any]] = []
    used_article_idxs: set = set()
    for row in low_conf_rows:
        if len(review_issues) >= int(max_items):
            break
        score = float(row.get("score", 0.0))
        if score < float(min_score):
            continue

        ia = find_idx(str(row.get("url_a", "")))
        ib = find_idx(str(row.get("url_b", "")))
        if ia is None or ib is None or ia == ib:
            continue
        if int(ia) in used_article_idxs or int(ib) in used_article_idxs:
            continue

        ra = df.loc[int(ia)]
        rb = df.loc[int(ib)]
        ta = to_kst_iso(ra.get("_dt"))
        tb = to_kst_iso(rb.get("_dt"))
        t_sorted = sorted([x for x in [ta, tb] if x])

        title_a = str(ra.get("title", ""))
        title_b = str(rb.get("title", ""))
        source_rep_title_raw = title_a if len(title_a) >= len(title_b) else title_b
        source_rep_title = _clean_title_text(source_rep_title_raw) or source_rep_title_raw
        rep_url = str(ra.get("url", "")) if source_rep_title_raw == title_a else str(rb.get("url", ""))

        sample_texts = [
            f"{title_a} {str(ra.get('content', ''))}",
            f"{title_b} {str(rb.get('content', ''))}",
        ]
        kws_raw = extract_keywords(sample_texts, topk=6)
        sum_lines = extractive_news_style_summary(
            [str(ra.get("content", "")), str(rb.get("content", ""))],
            max_lines=5,
            min_lines=3
        )
        sum_lines = refine_summary_lines_by_focus(
            sum_lines,
            representative_title=source_rep_title,
            keywords=kws_raw,
            max_lines=5,
            min_lines=3
        )
        if not sum_lines:
            sum_lines = post_clean_summary_lines(
                [f"- {_clean_title_text(title_a) or title_a}", f"- {_clean_title_text(title_b) or title_b}"]
            )[:5]
        kws = clean_review_keywords(
            keywords=kws_raw,
            representative_title=source_rep_title,
            summary_lines=sum_lines,
            max_k=6,
            min_k=REVIEW_KEYWORD_MIN_K
        )
        rep_title = source_rep_title
        if bool(generate_title) and (not bool(force_source_title)):
            rep_title = compose_issue_title(
                source_title=source_rep_title,
                keywords=kws,
                summary_lines=sum_lines,
                max_chars=int(title_max_chars),
                candidate_titles=[title_a, title_b]
            )
        rep_title = _clean_title_text(rep_title) or source_rep_title

        arts = []
        for r in [ra, rb]:
            arts.append({
                "domain": str(r.get("domain", "")),
                "date": str(r.get("date", "")),
                "category": str(r.get("category", "")),
                "title": str(r.get("title", "")),
                "url": str(r.get("url", "")),
            })

        doms = set(x.get("domain", "") for x in arts if x.get("domain", ""))
        if len(doms) < 2 and score < float(same_domain_strong_score):
            continue

        ridx = len(review_issues) + 1
        review_issues.append({
            "issue_id": f"{bucket_key}__R{ridx:03d}",
            "bucket": bucket_key,
            "issue_type": "review_needed",
            "time_start": t_sorted[0] if t_sorted else "",
            "time_end": t_sorted[-1] if t_sorted else "",
            "representative_title": rep_title,
            "source_representative_title": source_rep_title,
            "representative_url": rep_url,
            "keywords": kws,
            "stats": {
                "size": 2,
                "domains": int(len(doms)),
                "low_conf_score": score,
                "cosine": float(row.get("cosine", 0.0)),
                "title_jaccard": float(row.get("title_jaccard", 0.0)),
                "lead_jaccard": float(row.get("lead_jaccard", 0.0)),
            },
            "summary_lines": sum_lines,
            "articles": arts,
        })
        used_article_idxs.add(int(ia))
        used_article_idxs.add(int(ib))
    return review_issues

def build_issue_articles_map(issues: List[Dict[str,Any]], out_csv: Path) -> None:
    rows = []
    for it in issues:
        issue_id = it.get("issue_id","")
        bucket = it.get("bucket","")
        arts = it.get("articles",[]) or []
        for rank, a in enumerate(arts, start=1):
            rows.append({
                "issue_id": issue_id,
                "bucket": bucket,
                "rank": rank,
                "domain": a.get("domain",""),
                "date": a.get("date",""),
                "category": a.get("category",""),
                "title": a.get("title",""),
                "url": a.get("url",""),
            })
    pd.DataFrame(rows).to_csv(out_csv, index=False, encoding="utf-8-sig")

def print_issue_preview(issues: List[Dict[str,Any]], max_n: int = 10, max_articles: int = 12) -> None:
    if not issues:
        print("\n===== PREVIEW(ISSUES) =====\n(no issues)")
        return
    print("\n===== PREVIEW(ISSUES) =====")
    for it in issues[:max_n]:
        print(f"\n이슈: {it.get('representative_title','')}")
        print(f"time: {it.get('time_start','')} ~ {it.get('time_end','')}")
        print(f"keywords: {', '.join(it.get('keywords',[]) or [])}")
        print(f"stats: {it.get('stats',{})}")
        print("summary:")
        for ln in it.get("summary_lines",[]) or []:
            print(ln)
        arts = it.get("articles", []) or []
        if arts:
            print("merged_articles:")
            for a in arts[:max_articles]:
                print(f"  - [{a.get('domain','')}] {a.get('title','')}")
                print(f"    {a.get('url','')}")

def print_review_issue_preview(review_issues: List[Dict[str,Any]], max_n: int = 3, max_articles: int = 2) -> None:
    if not review_issues:
        return
    print("\n===== PREVIEW(REVIEW-NEEDED) =====")
    for it in review_issues[:max_n]:
        print(f"\n검토이슈: {it.get('representative_title','')}")
        print(f"time: {it.get('time_start','')} ~ {it.get('time_end','')}")
        print(f"keywords: {', '.join(it.get('keywords',[]) or [])}")
        print(f"stats: {it.get('stats',{})}")
        print("summary:")
        for ln in it.get("summary_lines",[]) or []:
            print(ln)
        arts = it.get("articles", []) or []
        if arts:
            print("candidate_articles:")
            for a in arts[:max_articles]:
                print(f"  - [{a.get('domain','')}] {a.get('title','')}")
                print(f"    {a.get('url','')}")

def print_singleton_preview(df_single: pd.DataFrame, max_n: int = 10) -> None:
    print("\n===== PREVIEW(SINGLETONS) =====")
    if df_single is None or len(df_single) == 0:
        print("(no singletons)")
        return
    for _, r in df_single.head(max_n).iterrows():
        print(f"- [{r.get('bucket_date','')}] {r.get('title','')}")
        print(f"  {r.get('url','')}")
        print(f"  reason: {r.get('reason','')}")

# =============================================================================
# Build one bucket
# =============================================================================
def build_bucket_from_df(
    cfg: PipelineConfig,
    bucket_key: str,
    df0: pd.DataFrame,
    embedder: KoE5Embedder,
) -> Tuple[List[Dict[str,Any]], pd.DataFrame, Dict[str,Any]]:
    """
     DB에서 미리 로드한 df0를 받아서 build_bucket 로직을 그대로 수행하는 버전
    - load_bucket_df(cfg, bucket_key, cache_dir) 호출만 제거
    - scan_stats는 빈 dict로 대체(필요하면 여기서 통계 직접 넣을 수도 있음)
    """
    paths = bucket_paths(cfg, bucket_key)
    out = Path(cfg.OUT_DIR)
    out.mkdir(parents=True, exist_ok=True)

    # 기존 build_bucket에 있던 cache_dir은 파일 로딩용이라 여기서는 유지해도 되고 안 써도 됨
    cache_dir = paths["cache_dir"]

    #  여기만 변경: 파일에서 읽지 않고, 입력 df0 그대로 사용
    scan_stats: Dict[str,Any] = {}
    docs_raw_bucket = int(len(df0))

    if len(df0) == 0:
        empty_single = pd.DataFrame(columns=["bucket_date","url","title","date","category","domain","reason"])
        empty_single.to_csv(paths["single_csv"], index=False, encoding="utf-8-sig")
        paths["single_json"].write_text("[]", encoding="utf-8")
        paths["issues_json"].write_text("[]", encoding="utf-8")
        paths["review_json"].write_text("[]", encoding="utf-8")
        issues_to_csv([], paths["review_csv"])
        paths["low_conf_json"].write_text("[]", encoding="utf-8")
        low_confidence_to_csv([], paths["low_conf_csv"])
        issues_to_csv([], paths["issues_csv"])
        build_issue_articles_map([], paths["map_csv"])
        stats = {
            "status": "ok_empty",
            "bucket": bucket_key,
            "docs_raw_bucket": 0,
            "docs_total": 0,
            "docs_in_multi": 0,
            "docs_in_singleton": 0,
            "multi_count": 0,
            "singleton_count": 0,
            "coverage": 0.0,
            "strict_dropped": 0,
            "minhash_dropped": 0,
            "suspicious_dropped": 0,
            "fallback_used": False,
            "tiny_rescue_used": False,
            "max_group_size": 0,
            "no_issue_reason": "empty_bucket",
            **scan_stats
        }
        write_done(paths["done"], cfg, stats)
        return [], empty_single, stats

    # =========================
    # 아래부터는 기존 build_bucket 본문을 그대로 복붙한 것 (df0부터 시작)
    # =========================

    # stage1 clean
    df = df0.copy()
    for c in REQUIRED_COLS:
        df[c] = df[c].astype(str).fillna("")
    df["title"] = df["title"].astype(str).apply(normalize_text)
    df["content"] = df["content"].astype(str).apply(normalize_text)
    df["domain"] = df["url"].astype(str).apply(safe_domain)

    df, strict_drop, mh_drop = dedup_articles(df, cfg)
    if strict_drop or mh_drop:
        print(f"[DEDUP] strict={strict_drop}, minhash={mh_drop}")

    df, susp_drop = drop_suspicious_rows(df, cfg)
    if susp_drop:
        print(f"[SUSP] dropped={susp_drop}")

    df1 = df.reset_index(drop=True)
    docs_total = int(len(df1))
    if docs_total == 0:
        empty_single = pd.DataFrame(columns=["bucket_date","url","title","date","category","domain","reason"])
        empty_single.to_csv(paths["single_csv"], index=False, encoding="utf-8-sig")
        paths["single_json"].write_text("[]", encoding="utf-8")
        paths["issues_json"].write_text("[]", encoding="utf-8")
        paths["review_json"].write_text("[]", encoding="utf-8")
        issues_to_csv([], paths["review_csv"])
        paths["low_conf_json"].write_text("[]", encoding="utf-8")
        low_confidence_to_csv([], paths["low_conf_csv"])
        issues_to_csv([], paths["issues_csv"])
        build_issue_articles_map([], paths["map_csv"])
        stats = {
            "status": "ok_filtered_empty",
            "bucket": bucket_key,
            "docs_raw_bucket": docs_raw_bucket,
            "docs_total": 0,
            "docs_in_multi": 0,
            "docs_in_singleton": 0,
            "multi_count": 0,
            "singleton_count": 0,
            "coverage": 0.0,
            "strict_dropped": int(strict_drop),
            "minhash_dropped": int(mh_drop),
            "suspicious_dropped": int(susp_drop),
            "fallback_used": False,
            "tiny_rescue_used": False,
            "max_group_size": 0,
            "no_issue_reason": "all_filtered_before_embed",
            **scan_stats
        }
        write_done(paths["done"], cfg, stats)
        print("[BUCKET] no documents left after dedup/suspicious filtering")
        return [], empty_single, stats

    titles_s = df1["title"].astype(str)
    contents_s = df1["content"].astype(str)
    leads_s = contents_s.str.slice(0, int(CONTENT_LEAD_CHARS))
    texts_for_embed = (titles_s + "\n" + leads_s).tolist()

    emb = embedder.encode(texts_for_embed, batch_size=int(cfg.EMB_BATCH_SIZE))


    # stage3 cluster
    fallback_used = False
    tiny_rescue_used = False
    max_group_size = 0
    if cfg.CLUSTER_MODE == "lsh" or len(df1) > cfg.KNN_MAX_N:
        groups = cluster_with_lsh_cosine(emb, texts_for_embed, cfg)
        max_group_size = max((len(v) for v in groups.values()), default=0)
    else:
        bcats = df1["category"].map(broad_category).fillna("unknown").astype(str).tolist()
        domain_keys = (df1["domain"].fillna("").astype(str) + "||" + pd.Series(bcats)).tolist()
        groups = cluster_domain_then_merge(
            emb=emb,
            titles=df1["title"].astype(str).tolist(),
            domain_keys=domain_keys,
            broad_cats=bcats,
            lead_texts=texts_for_embed,
            cfg=cfg
        )
        max_group_size = max((len(v) for v in groups.values()), default=0)
        if docs_total < 80 and max_group_size < int(cfg.MIN_ISSUE_SIZE):
            fallback_cfg = PipelineConfig(**asdict(cfg))
            fallback_cfg.CROSS_DOMAIN_COS_TH = min(float(cfg.CROSS_DOMAIN_COS_TH), 0.84)
            fallback_cfg.TITLE_JACC_TH = min(float(cfg.TITLE_JACC_TH), 0.12)
            fallback_cfg.IN_DOMAIN_TITLE_JACC_TH = min(float(cfg.IN_DOMAIN_TITLE_JACC_TH), 0.05)
            fallback_cfg.CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT = True
            groups = cluster_domain_then_merge(
                emb=emb,
                titles=df1["title"].astype(str).tolist(),
                domain_keys=domain_keys,
                broad_cats=bcats,
                lead_texts=texts_for_embed,
                cfg=fallback_cfg
            )
            fallback_used = True
            print(f"[FALLBACK] relaxed recluster applied (docs={docs_total})")

            # Tiny buckets can still stay all-singleton after domain-merge guards.
            # In that case, run one lexical+semantic rescue pass without domain/category constraints.
            max_group_size = max((len(v) for v in groups.values()), default=0)
            if max_group_size < int(cfg.MIN_ISSUE_SIZE):
                lsh_cfg = PipelineConfig(**asdict(cfg))
                lsh_cfg.MINHASH_TH = min(float(cfg.MINHASH_TH), 0.30)
                lsh_cfg.COS_TH = min(float(cfg.COS_TH), 0.78)
                groups = cluster_with_lsh_cosine(emb, texts_for_embed, lsh_cfg)
                max_group_size = max((len(v) for v in groups.values()), default=0)
                tiny_rescue_used = True
                print(f"[FALLBACK] tiny-bucket lsh rescue applied (max_group={max_group_size})")

                if max_group_size < int(cfg.MIN_ISSUE_SIZE):
                    uf_tiny = UnionFind(len(df1))
                    idxs_all = np.arange(len(df1), dtype=int)
                    edges_tiny = knn_edges_cos(emb, idxs_all, topk=min(10, len(df1)-1), th=0.80)
                    titles_all = df1["title"].astype(str).tolist()
                    for a, b in edges_tiny:
                        tj = title_jaccard(titles_all[a], titles_all[b])
                        lt = text_token_jaccard(texts_for_embed[a], texts_for_embed[b], max_tok=120)
                        if tj >= 0.03 or lt >= 0.04:
                            uf_tiny.union(a, b)
                    groups = uf_tiny.groups()
                    max_group_size = max((len(v) for v in groups.values()), default=0)
                    tiny_rescue_used = True
                    print(f"[FALLBACK] tiny-bucket knn rescue applied (max_group={max_group_size})")
    max_group_size = max((len(v) for v in groups.values()), default=0)

    effective_min_rep_min = float(cfg.MIN_REP_MIN)
    if fallback_used:
        effective_min_rep_min = min(effective_min_rep_min, 0.55)
    if tiny_rescue_used:
        effective_min_rep_min = min(effective_min_rep_min, 0.45)

    emit_singletons = bool(getattr(cfg, "EMIT_SINGLETONS", False))
    issues: List[Dict[str,Any]] = []
    singleton_rows: List[Dict[str,Any]] = []
    multi_count = 0
    geo_pruned_total = 0

    group_items = sorted(groups.items(), key=lambda kv: len(kv[1]), reverse=True)
    titles_all = df1["title"].astype(str).tolist()
    for gi, (_root, members) in enumerate(group_items, start=1):
        members = sorted(set(int(x) for x in members))
        if not members:
            continue

        # Quality gate for tiny-bucket rescue: avoid forcing weak 2-article, single-source issues.
        if tiny_rescue_used:
            dom_n = len(set(str(df1.loc[i, "domain"]) for i in members))
            if len(members) <= 2 and dom_n < 2:
                if emit_singletons:
                    for i in members:
                        r = df1.loc[i]
                        singleton_rows.append({
                            "bucket_date": bucket_key,
                            "url": str(r.get("url","")),
                            "title": str(r.get("title","")),
                            "date": str(r.get("date","")),
                            "category": str(r.get("category","")),
                            "domain": str(r.get("domain","")),
                            "reason": "tiny_rescue_low_diversity",
                        })
                continue
            if len(members) == 2:
                a, b = members[0], members[1]
                tj = title_jaccard(str(df1.loc[a, "title"]), str(df1.loc[b, "title"]))
                lt = text_token_jaccard(texts_for_embed[a], texts_for_embed[b], max_tok=140)
                if tj < 0.08 and lt < 0.12:
                    if emit_singletons:
                        for i in members:
                            r = df1.loc[i]
                            singleton_rows.append({
                                "bucket_date": bucket_key,
                                "url": str(r.get("url","")),
                                "title": str(r.get("title","")),
                                "date": str(r.get("date","")),
                                "category": str(r.get("category","")),
                                "domain": str(r.get("domain","")),
                                "reason": "tiny_rescue_weak_pair",
                            })
                    continue

        # Local incident clusters (e.g., wildfire/accident) should keep geographic consistency.
        tmp_rep = pick_representative(members, emb)
        members, geo_dropped = prune_geo_mismatch_members(
            members=members,
            titles=titles_all,
            rep_idx=tmp_rep,
            min_keep=int(cfg.MIN_ISSUE_SIZE)
        )
        if geo_dropped:
            geo_pruned_total += int(len(geo_dropped))
            if emit_singletons:
                for i in geo_dropped:
                    r = df1.loc[i]
                    singleton_rows.append({
                        "bucket_date": bucket_key,
                        "url": str(r.get("url","")),
                        "title": str(r.get("title","")),
                        "date": str(r.get("date","")),
                        "category": str(r.get("category","")),
                        "domain": str(r.get("domain","")),
                        "reason": "geo_mismatch_local_incident",
                    })

        rep = pick_representative(members, emb)
        metrics = compute_cluster_metrics(members, emb, rep_idx=rep, sample_pairs=250)
        metric_val = float(metrics.get(cfg.COHESION_METRIC, 0.0))
        if cfg.MIN_COHESION and metric_val < float(cfg.MIN_COHESION):
            if emit_singletons:
                for i in members:
                    r = df1.loc[i]
                    singleton_rows.append({
                        "bucket_date": bucket_key,
                        "url": str(r.get("url","")),
                        "title": str(r.get("title","")),
                        "date": str(r.get("date","")),
                        "category": str(r.get("category","")),
                        "domain": str(r.get("domain","")),
                        "reason": "low_cohesion",
                    })
            continue

        if effective_min_rep_min > 0.0 and float(metrics.get("rep_min", 1.0)) < effective_min_rep_min:
            if emit_singletons:
                for i in members:
                    r = df1.loc[i]
                    singleton_rows.append({
                        "bucket_date": bucket_key,
                        "url": str(r.get("url","")),
                        "title": str(r.get("title","")),
                        "date": str(r.get("date","")),
                        "category": str(r.get("category","")),
                        "domain": str(r.get("domain","")),
                        "reason": "low_rep_min",
                    })
            continue

        if len(members) < int(cfg.MIN_ISSUE_SIZE):
            reason = "cluster_size_1" if len(members) == 1 else "below_min_issue_size"
            if emit_singletons:
                for i in members:
                    r = df1.loc[i]
                    singleton_rows.append({
                        "bucket_date": bucket_key,
                        "url": str(r.get("url","")),
                        "title": str(r.get("title","")),
                        "date": str(r.get("date","")),
                        "category": str(r.get("category","")),
                        "domain": str(r.get("domain","")),
                        "reason": reason,
                    })
            continue

        ordered = ordered_by_centroid(members, emb)
        sample_idx = ordered[: min(16, len(ordered))]
        sample_texts = [(str(df1.loc[i,"title"]) + " " + str(df1.loc[i,"content"])) for i in sample_idx]
        kws = extract_keywords(sample_texts, topk=8)
        rep_row = df1.loc[rep]

        # summary: rep + top centroid docs
        contents_for_sum = []
        def add_sum(i: int) -> None:
            t = str(df1.loc[i,"title"])
            c = str(df1.loc[i,"content"])
            if c.strip() and not content_suspicious(t, c, cfg):
                contents_for_sum.append(c)
        add_sum(rep)
        for i in sample_idx:
            if i != rep:
                add_sum(int(i))
        if not contents_for_sum:
            contents_for_sum = [str(df1.loc[rep,"content"])]
        sum_lines = extractive_news_style_summary(contents_for_sum, max_lines=7, min_lines=5)
        sum_lines = refine_summary_lines_by_focus(
            sum_lines,
            representative_title=str(rep_row.get("title", "")),
            keywords=kws,
            max_lines=7,
            min_lines=4
        )
        source_rep_title_raw = str(rep_row.get("title",""))
        source_rep_title = _clean_title_text(source_rep_title_raw) or source_rep_title_raw
        generated_title = source_rep_title
        if bool(getattr(cfg, "GENERATE_ISSUE_TITLE", True)) and (not bool(getattr(cfg, "FORCE_SOURCE_TITLE", False))):
            generated_title = compose_issue_title(
                source_title=source_rep_title,
                keywords=kws,
                summary_lines=sum_lines,
                max_chars=int(getattr(cfg, "GENERATED_TITLE_MAX_CHARS", 64)),
                candidate_titles=[str(df1.loc[i, "title"]) for i in ordered[: min(12, len(ordered))]]
            )
        generated_title = _clean_title_text(generated_title) or source_rep_title

        dts = pd.to_datetime(df1.loc[members, "_dt"], errors="coerce")
        tmin = pd.to_datetime(dts.min()).to_pydatetime().replace(tzinfo=KST)
        tmax = pd.to_datetime(dts.max()).to_pydatetime().replace(tzinfo=KST)

        issue_id = f"{bucket_key}__{gi:04d}"

        related_urls = [str(df1.loc[i, "url"]) for i in ordered]

        issue_obj: Dict[str,Any] = {
            "issue_id": issue_id,
            "bucket": bucket_key,
            "time_start": tmin.isoformat(timespec="seconds"),
            "time_end": tmax.isoformat(timespec="seconds"),
            "representative_title": generated_title,
            "source_representative_title": source_rep_title,
            "representative_url": str(rep_row.get("url","")),
            "keywords": kws,

            # ✅ 추가: 이 이슈에 묶인 기사 수/목록을 top-level로도 항상 제공
            "related_count": int(len(members)),
            "related_urls": related_urls,

            "stats": {
                # ✅ 기존 그대로 (여기도 동일한 값)
                "size": int(len(members)),
                "domains": int(len(set(str(df1.loc[i,"domain"]) for i in members))),
                "centroid_mean": float(metrics["centroid_mean"]),
                "rep_mean": float(metrics["rep_mean"]),
                "intra_sample_mean": float(metrics["intra_sample_mean"]),
                "rep_min": float(metrics.get("rep_min", 0.0)),
            },
            "summary_lines": sum_lines,
        }

        if cfg.INCLUDE_ARTICLES_IN_JSON:
            arts = []
            for i in ordered:
                r = df1.loc[i]
                arts.append({
                    "domain": str(r.get("domain","")),
                    "date": str(r.get("date","")),
                    "category": str(r.get("category","")),
                    "title": str(r.get("title","")),
                    "url": str(r.get("url","")),
                })
            issue_obj["articles"] = arts

        issues.append(issue_obj)
        multi_count += 1

    if emit_singletons:
        df_single = pd.DataFrame(singleton_rows, columns=["bucket_date","url","title","date","category","domain","reason"])
    else:
        df_single = pd.DataFrame(columns=["bucket_date","url","title","date","category","domain","reason"])
    df_single.to_csv(paths["single_csv"], index=False, encoding="utf-8-sig")
    paths["single_json"].write_text(json.dumps(singleton_rows, ensure_ascii=False, indent=2), encoding="utf-8")

    paths["issues_json"].write_text(json.dumps(issues, ensure_ascii=False, indent=2), encoding="utf-8")
    issues_to_csv(issues, paths["issues_csv"])
    build_issue_articles_map(issues, paths["map_csv"])

    low_conf_rows: List[Dict[str,Any]] = []
    if bool(getattr(cfg, "ENABLE_LOW_CONF_OUTPUT", True)) and docs_total > 1 and int(multi_count) == 0:
        low_conf_rows = collect_low_confidence_pairs(
            df=df1,
            emb=emb,
            texts_for_embed=texts_for_embed,
            bucket_key=bucket_key,
            max_pairs=int(getattr(cfg, "LOW_CONF_PAIR_MAX", 30))
        )
        if low_conf_rows:
            print(f"[LOW-CONF] saved candidate pairs={len(low_conf_rows)}")
    paths["low_conf_json"].write_text(json.dumps(low_conf_rows, ensure_ascii=False, indent=2), encoding="utf-8")
    low_confidence_to_csv(low_conf_rows, paths["low_conf_csv"])

    review_issues: List[Dict[str,Any]] = []
    if int(multi_count) == 0 and bool(getattr(cfg, "ENABLE_LOW_CONF_REVIEW_ISSUES", True)):
        review_issues = build_review_issues_from_low_conf(
            df=df1,
            low_conf_rows=low_conf_rows,
            bucket_key=bucket_key,
            max_items=int(getattr(cfg, "LOW_CONF_REVIEW_MAX", 3)),
            min_score=float(getattr(cfg, "LOW_CONF_REVIEW_MIN_SCORE", 0.66)),
            same_domain_strong_score=float(getattr(cfg, "LOW_CONF_REVIEW_SAME_DOMAIN_STRONG_SCORE", 0.74)),
            generate_title=bool(getattr(cfg, "GENERATE_ISSUE_TITLE", True)),
            title_max_chars=int(getattr(cfg, "GENERATED_TITLE_MAX_CHARS", 64)),
            force_source_title=bool(getattr(cfg, "FORCE_SOURCE_TITLE", False))
        )
        if review_issues:
            print(f"[REVIEW] promoted review-needed issues={len(review_issues)}")
    paths["review_json"].write_text(json.dumps(review_issues, ensure_ascii=False, indent=2), encoding="utf-8")
    issues_to_csv(review_issues, paths["review_csv"])
    if int(geo_pruned_total) > 0:
        print(f"[GEO] pruned local-incident geo mismatches={int(geo_pruned_total)}")

    docs_in_multi = int(sum(int(it.get("stats", {}).get("size", 0)) for it in issues))
    docs_in_singleton = int(len(df_single))
    coverage = float(docs_in_multi / docs_total) if docs_total > 0 else 0.0

    no_issue_reason = ""
    if int(multi_count) == 0:
        if len(review_issues) > 0:
            no_issue_reason = "review_needed_from_low_conf"
        elif max_group_size < int(cfg.MIN_ISSUE_SIZE):
            no_issue_reason = "all_singletons_after_clustering"
        elif tiny_rescue_used:
            no_issue_reason = "tiny_bucket_quality_gate_filtered"
        else:
            no_issue_reason = "quality_gate_filtered_all"
        print(f"[BUCKET] no issues created (reason={no_issue_reason})")

    status = "ok"
    if int(multi_count) == 0:
        status = "ok_review_only" if len(review_issues) > 0 else "ok_no_issues"

    stats = {
        "status": status,
        "bucket": bucket_key,
        "docs_raw_bucket": docs_raw_bucket,
        "docs_total": docs_total,
        "docs_in_multi": docs_in_multi,
        "docs_in_singleton": docs_in_singleton,
        "multi_count": int(multi_count),
        "singleton_count": docs_in_singleton,
        "coverage": coverage,
        "strict_dropped": int(strict_drop),
        "minhash_dropped": int(mh_drop),
        "suspicious_dropped": int(susp_drop),
        "fallback_used": bool(fallback_used),
        "tiny_rescue_used": bool(tiny_rescue_used),
        "max_group_size": int(max_group_size),
        "geo_pruned": int(geo_pruned_total),
        "low_conf_candidates": int(len(low_conf_rows)),
        "review_issue_count": int(len(review_issues)),
        "no_issue_reason": no_issue_reason,
        **scan_stats
    }
    write_done(paths["done"], cfg, stats)
    return issues, df_single, stats

# =============================================================================
# Run pipeline
# =============================================================================
def run_pipeline(cfg: PipelineConfig) -> None:
    if not (_HAVE_TORCH and _HAVE_TRANSFORMERS):
        print("====================================================")
        print("[FATAL] torch/transformers 가 설치되어 있지 않아 실행할 수 없습니다.")
        print(" - torch import:", "OK" if _HAVE_TORCH else f"FAIL ({_TORCH_ERR})")
        print(" - transformers import:", "OK" if _HAVE_TRANSFORMERS else f"FAIL ({_TRANSFORMERS_ERR})")
        print("====================================================")
        return

    # wire tuning panel -> cfg
    cfg.MIN_ISSUE_SIZE = int(MIN_ISSUE_SIZE)
    cfg.IN_DOMAIN_COS_TH = float(IN_DOMAIN_COS_TH)
    cfg.CROSS_DOMAIN_COS_TH = float(CROSS_DOMAIN_COS_TH)
    cfg.TITLE_JACC_TH = float(TITLE_JACC_TH)
    cfg.IN_DOMAIN_TITLE_JACC_TH = float(IN_DOMAIN_TITLE_JACC_TH)
    cfg.KNN_MAX_NEIGHBORS = int(KNN_MAX_NEIGHBORS)
    cfg.MERGE_REQUIRE_SAME_BROAD_CAT = bool(MERGE_REQUIRE_SAME_BROAD_CAT)
    cfg.CROSS_DOMAIN_LEAD_JACC_TH = float(CROSS_DOMAIN_LEAD_JACC_TH)
    cfg.CROSS_DOMAIN_STRONG_COS_TH = float(CROSS_DOMAIN_STRONG_COS_TH)
    cfg.CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT = bool(CROSS_DOMAIN_ALLOW_UNKNOWN_BCAT)

    cfg.DEDUP_USE_MINHASH = bool(DEDUP_USE_MINHASH)
    cfg.DEDUP_SIM_THRESHOLD = float(DEDUP_SIM_THRESHOLD)

    cfg.SUSP_MIN_CONTENT_CHARS = int(SUSP_MIN_CONTENT_CHARS)
    cfg.SUSP_HEAD_MAX_CHARS = int(SUSP_HEAD_MAX_CHARS)
    cfg.SUSP_NEED_HITS_SHORT = int(SUSP_NEED_HITS_SHORT)
    cfg.SUSP_NEED_HITS_LONG = int(SUSP_NEED_HITS_LONG)

    cfg.COHESION_METRIC = str(COHESION_METRIC)
    cfg.MIN_COHESION = float(MIN_COHESION)
    cfg.EMB_BATCH_SIZE = int(EMB_BATCH_SIZE)

    cfg.STAR_SPLIT_ENABLE = bool(STAR_SPLIT_ENABLE)
    cfg.STAR_SIM_TH = float(STAR_SIM_TH)
    cfg.STAR_TITLE_JACC_TH = float(STAR_TITLE_JACC_TH)
    cfg.MIN_REP_MIN = float(MIN_REP_MIN)
    cfg.EMIT_SINGLETONS = bool(EMIT_SINGLETONS)
    cfg.ENABLE_LOW_CONF_OUTPUT = bool(ENABLE_LOW_CONF_OUTPUT)
    cfg.LOW_CONF_PAIR_MAX = int(LOW_CONF_PAIR_MAX)
    cfg.ENABLE_LOW_CONF_REVIEW_ISSUES = bool(ENABLE_LOW_CONF_REVIEW_ISSUES)
    cfg.LOW_CONF_REVIEW_MAX = int(LOW_CONF_REVIEW_MAX)
    cfg.LOW_CONF_REVIEW_MIN_SCORE = float(LOW_CONF_REVIEW_MIN_SCORE)
    cfg.LOW_CONF_REVIEW_SAME_DOMAIN_STRONG_SCORE = float(LOW_CONF_REVIEW_SAME_DOMAIN_STRONG_SCORE)
    cfg.GENERATE_ISSUE_TITLE = bool(GENERATE_ISSUE_TITLE)
    cfg.GENERATED_TITLE_MAX_CHARS = int(GENERATED_TITLE_MAX_CHARS)
    cfg.FORCE_SOURCE_TITLE = bool(FORCE_SOURCE_TITLE)

    set_seed(cfg.RANDOM_SEED)
    out_dir = Path(cfg.OUT_DIR)
    out_dir.mkdir(parents=True, exist_ok=True)

    print("[SCAN] counting buckets ...")
    src_n = sum(1 for _ in iter_input_sources(cfg.CSV_PATH))
    if src_n == 0:
        print("====================================================")
        print("[FATAL] 입력 소스를 찾지 못했습니다.")
        print(f" - CSV_PATH: {cfg.CSV_PATH}")
        print(" - 경로가 올바른지, 드라이브 마운트 상태인지 확인하세요.")
        print("====================================================")
        return

    counts, dropped_no_date = count_buckets(cfg)
    buckets = select_target_buckets(counts, cfg)
    print(f"[SCAN] BUCKET={cfg.BUCKET} | MAX_BUCKETS={cfg.MAX_BUCKETS}")
    print(f"[SCAN] selected buckets: {buckets}")
    print(f"[SCAN] dropped(no date): {dropped_no_date}")

    if not buckets:
        print("====================================================")
        print("[FATAL] 처리할 bucket이 없습니다.")
        print(" - date 파싱 실패 또는 TARGET_BUCKETS/MAX_BUCKETS 설정을 확인하세요.")
        print(f" - dropped(no date): {dropped_no_date}")
        print("====================================================")
        return

    device = get_device(cfg.DEVICE)
    print(f"device: {device}")
    embedder = KoE5Embedder(cfg.E5_MODEL, device=device, max_length=512)

    bucket_stats: List[Dict[str,Any]] = []
    failed_buckets: List[Dict[str,str]] = []
    for b in buckets:
        print("\n" + "="*70)
        print(f"[BUCKET] {b} (count={counts.get(b,0)})")
        try:
            issues, df_single, st = build_bucket(cfg, b, embedder)
            bucket_stats.append(st)
            print(f"[BUCKET-STATS] bucket={b} | docs_total={st.get('docs_total',0)} | multi={st.get('multi_count',0)} | singleton={st.get('singleton_count',0)} | coverage={float(st.get('coverage',0.0)):.3f}")
            print_issue_preview(issues, max_n=int(ISSUE_PREVIEW_MAX), max_articles=int(ISSUE_ARTICLE_PREVIEW_MAX))
            if int(st.get("review_issue_count", 0)) > 0:
                try:
                    rv_path = bucket_paths(cfg, b)["review_json"]
                    rv = json.loads(rv_path.read_text(encoding="utf-8"))
                    print_review_issue_preview(rv, max_n=min(int(cfg.LOW_CONF_REVIEW_MAX), 3), max_articles=2)
                except Exception as _:
                    pass
            if cfg.EMIT_SINGLETONS and int(SINGLETON_PREVIEW_MAX) > 0:
                print_singleton_preview(df_single, max_n=int(SINGLETON_PREVIEW_MAX))
        except Exception as e:
            err = repr(e)
            failed_buckets.append({"bucket": b, "error": err})
            print(f"[BUCKET-ERROR] bucket={b} | error={err}")
            try:
                fail_done = bucket_paths(cfg, b)["done"]
                write_done(fail_done, cfg, {"status": "failed", "bucket": b, "error": err})
            except Exception:
                pass

    ok_count = len(bucket_stats)
    fail_count = len(failed_buckets)
    total_docs = int(sum(int(x.get("docs_total", 0)) for x in bucket_stats))
    total_multi = int(sum(int(x.get("multi_count", 0)) for x in bucket_stats))
    print("\n" + "="*70)
    print(f"[RUN-SUMMARY] buckets_ok={ok_count} | buckets_failed={fail_count} | docs_total={total_docs} | multi_total={total_multi}")
    if failed_buckets:
        for it in failed_buckets:
            print(f" - failed bucket={it.get('bucket','')} | error={it.get('error','')}")

# =========================
# FastAPI (tracking service)
# =========================
import os
import pymysql
from fastapi import FastAPI, HTTPException

app = FastAPI()

# =========================
# DB 연결
# =========================

DEFAULT_OUT_DIR = os.getenv("OUT_DIR", "/app/issue_outputs")
DEFAULT_BUCKET = os.getenv("BUCKET", "day")
DEFAULT_MAX_BUCKETS = int(os.getenv("MAX_BUCKETS", "2"))
DEFAULT_E5_MODEL = os.getenv("E5_MODEL", "intfloat/multilingual-e5-base")
DEFAULT_DEVICE = os.getenv("DEVICE", "cpu")  # cuda 쓰면 "cuda"
DEFAULT_MODEL_DIR = os.getenv("MODEL_DIR", "")  # 로컬 모델 경로 쓸 때만


def get_conn():
    return pymysql.connect(
        host=DB_HOST,
        port=DB_PORT,
        user=DB_USER,
        password=DB_PASSWORD,
        db=DB_NAME,
        charset="utf8mb4",
        autocommit=True,
        cursorclass=pymysql.cursors.DictCursor,
    )

def make_cfg() -> "PipelineConfig":
    cfg = PipelineConfig(
        CSV_PATH="",                 # DB 사용하므로 의미 없음
        OUT_DIR=DEFAULT_OUT_DIR,
        BUCKET=DEFAULT_BUCKET,
        MAX_BUCKETS=DEFAULT_MAX_BUCKETS,
    )
    # ✅ PipelineConfig에 해당 필드가 "원래" 없을 수도 있으니 동적으로 주입
    cfg.E5_MODEL = DEFAULT_E5_MODEL
    cfg.DEVICE = DEFAULT_DEVICE
    cfg.MODEL_DIR = DEFAULT_MODEL_DIR
    return cfg

import json  # 파일 상단에 없으면 추가

import json

def find_article_id_by_url(url: str):
    if not url:
        return None
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT id FROM articles WHERE url=%s LIMIT 1", (url,))
            row = cur.fetchone()
            return int(row["id"]) if row else None
    finally:
        conn.close()


def _infer_related_count(issue: dict) -> int:
    # 1) top-level related_count 우선
    rc = issue.get("related_count")
    if isinstance(rc, (int, float)) and rc > 0:
        return int(rc)
    if isinstance(rc, str) and rc.isdigit():
        return int(rc)

    # 2) stats.size fallback
    size = (issue.get("stats") or {}).get("size")
    if isinstance(size, (int, float)) and size > 0:
        return int(size)
    if isinstance(size, str) and size.isdigit():
        return int(size)

    # 3) articles 목록 fallback (INCLUDE_ARTICLES_IN_JSON 켰을 때)
    arts = issue.get("articles")
    if isinstance(arts, list) and len(arts) > 0:
        return len(arts)

    return 1


def _resolve_article_id(issue: dict) -> int | None:
    # 대표 URL로 먼저 찾기
    rep_url = str(issue.get("representative_url", "")).strip()
    article_id = find_article_id_by_url(rep_url)
    if article_id:
        return article_id

    # 대표 URL이 DB에 없으면, issue["articles"]가 있으면 거기서 하나라도 찾아보기(옵션)
    arts = issue.get("articles")
    if isinstance(arts, list):
        for a in arts[:10]:  # 너무 길면 10개만
            u = str((a or {}).get("url", "")).strip()
            article_id = find_article_id_by_url(u)
            if article_id:
                return article_id

    print("[WARN] article_id not found for representative_url:", rep_url)
    return None


def upsert_issue_summary(issue: dict) -> None:
    article_id = _resolve_article_id(issue)
    if not article_id:
        return

    short_summary = "\n".join(issue.get("summary_lines", []) or [])
    ultra_short = str(issue.get("representative_title", "") or "").strip()
    keywords_json = json.dumps(issue.get("keywords", []) or [], ensure_ascii=False)

    rep_url = str(issue.get("representative_url", "")).strip()
    background = f"{issue.get('source_representative_title','')}\n{rep_url}"

    related_count = _infer_related_count(issue)

    conn = get_conn()
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO issue_summaries
                  (article_id, related_count, short_summary, ultra_short, background, keywords, created_at)
                VALUES
                  (%s, %s, %s, %s, %s, %s, NOW())
                ON DUPLICATE KEY UPDATE
                  related_count=VALUES(related_count),
                  short_summary=VALUES(short_summary),
                  ultra_short=VALUES(ultra_short),
                  background=VALUES(background),
                  keywords=VALUES(keywords),
                  created_at=NOW()
                """,
                (article_id, related_count, short_summary, ultra_short, background, keywords_json),
            )
    finally:
        conn.close()

def load_articles_from_db(cfg: PipelineConfig) -> pd.DataFrame:
    """
    ✅ articles 테이블에서 '가장 최신 published_at' 날짜를 기준으로
    그 날짜 구간의 기사들을 가져온다.
    (기존처럼 NOW()-2DAY 고정조건 때문에 0건 나오는 문제 방지)
    """
    conn = get_conn()
    try:
        with conn.cursor() as cur:
            # 1) 최신 published_at 찾기 (0값/NULL 방지)
            cur.execute(
                """
                SELECT MAX(published_at) AS max_dt
                FROM articles
                WHERE published_at IS NOT NULL
                  AND published_at > '2000-01-01 00:00:00'
                """
            )
            row = cur.fetchone()
            max_dt = row["max_dt"] if row else None

            if not max_dt:
                print("[DB] MAX(published_at) is NULL -> no usable rows")
                return pd.DataFrame(columns=["url","title","thumbnail","content","date","category","_dt","domain"])

            # 2) 최신 날짜 기준으로 하루치(원하면 2일치로 확장 가능)
            #    DATE(max_dt) 00:00:00 ~ DATE(max_dt)+1일 미만
            cur.execute(
                """
                SELECT
                  url, title, thumbnail, content,
                  published_at, category
                FROM articles
                WHERE published_at >= DATE(%s)
                  AND published_at <  DATE(%s) + INTERVAL 1 DAY
                ORDER BY published_at DESC
                LIMIT %s
                """,
                (max_dt, max_dt, int(cfg.MAX_DOCS_PER_BUCKET)),
            )
            rows = cur.fetchall()

            print(f"[DB] max_dt={max_dt} | fetched_rows={len(rows)}")
    finally:
        conn.close()

    if not rows:
        return pd.DataFrame(columns=["url","title","thumbnail","content","date","category","_dt","domain"])

    df = pd.DataFrame(rows)
    df["date"] = df["published_at"].astype(str)
    df["_dt"] = pd.to_datetime(df["published_at"], errors="coerce")
    df["domain"] = df["url"].astype(str).apply(safe_domain)

    # null 안전
    for col in ["thumbnail","category","title","content","url"]:
        if col in df.columns:
            df[col] = df[col].where(df[col].notna(), "")

    return df[["url","title","thumbnail","content","date","category","_dt","domain"]]

def run_pipeline_db(cfg: PipelineConfig) -> Dict[str, Any]:
    df_all = load_articles_from_db(cfg)
    total = int(len(df_all))

    if total == 0:
        return {
            "ok": True,
            "message": "no articles loaded",
            "issues_saved": 0,
            "debug": {
                "hint": "articles에서 최신 published_at 기준으로 가져왔는데도 0이면, published_at 값이 비정상(0/NULL/문자열)일 가능성이 큼"
            },
            "buckets": []
        }

    latest_dt = df_all["_dt"].max()
    latest_day = latest_dt.date()
    bucket_key = str(latest_day)
    df_bucket = df_all[df_all["_dt"].dt.date == latest_day].copy()

    # ✅ 핵심: KoE5Embedder는 model_name, device가 필수
    device = get_device(getattr(cfg, "DEVICE", "cpu"))
    model_name = getattr(cfg, "E5_MODEL", "intfloat/multilingual-e5-base")
    model_dir = getattr(cfg, "MODEL_DIR", "") or None

    # ✅ model_dir을 지원하는 구현/안하는 구현 둘 다 안전하게 처리
    try:
        if model_dir:
            embedder = KoE5Embedder(model_name, device=device, max_length=512, model_dir=model_dir)
        else:
            embedder = KoE5Embedder(model_name, device=device, max_length=512)
    except TypeError:
        # KoE5Embedder가 model_dir 인자를 안 받는 버전일 때
        embedder = KoE5Embedder(model_name, device=device, max_length=512)

    issues, df_single, stats = build_bucket_from_df(cfg, bucket_key, df_bucket, embedder)

    saved = 0
    for issue in issues:
        upsert_issue_summary(issue)   
        saved += 1

    return {
        "ok": True,
        "bucket": bucket_key,
        "docs_loaded": total,
        "latest_dt": str(latest_dt),
        "docs_used_in_bucket": int(len(df_bucket)),
        "issues_saved": saved,
        "stats": stats,
    }

@app.get("/health")
def health():
    try:
        conn = get_conn()
        with conn.cursor() as cur:
            cur.execute("SELECT 1 AS ok")
            ping = cur.fetchone()
            cur.execute("SELECT COUNT(*) AS cnt FROM articles")
            cnt = cur.fetchone()
        conn.close()
        return {
            "ok": True,
            "db": ping,
            "articles_count": cnt["cnt"],
            "db_host": DB_HOST,
            "db_port": DB_PORT,
            "db_name": DB_NAME,
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.get("/run")
def run():
    try:
        print("[RUN] /run called - starting pipeline")
        cfg = make_cfg()
        return run_pipeline_db(cfg)
    except Exception as e:
        return {"ok": False, "error": repr(e), "trace": traceback.format_exc()[-2000:]}

#  로컬에서 python tracking_summary.py로 실행할 때도 돌아가게 (선택)
if __name__ == "__main__":
    # 로컬 실행 시에도 환경변수로 바꿀 수 있음
    cfg = make_cfg()
    run_pipeline(cfg)
